### ISSUE TITLE
Running resolve-based app in IE 11

### ISSUE THREAD

**Issue by sokolov11** [reimagined/resolve#1000]
**Describe the bug**
Example Shopping list doesn't work properly under IE11

**To Reproduce**
```
npx create-resolve-app@0.19.8 test-app -e shopping-list
cd test-app
yarn dev
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26894792/54188790-8444f780-44c1-11e9-9fb9-a81f2fc01448.png)
![image](https://user-images.githubusercontent.com/26894792/54188830-94f56d80-44c1-11e9-8a5f-c9dc1152f8de.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: IE
 - Version 11

**Comment by MrCheater** [comment]
Fixed in version 0.20.1
