### ISSUE TITLE
controller in the apiHandler config should be called "handler"

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#1001]
https://github.com/reimagined/resolve/blob/84b34ef55503c61e97bfab94a3ebef8a2c040bbc/packages/core/resolve-scripts/configs/schema.resolve.config.json#L200

I'm describing apiHandler, so it is called handler. It is not a controller, since there is no controllers here. Otherwise it would be called "apiController"

**Comment by MrCheater** [comment]
Fixed in version 0.24.2 https://github.com/reimagined/resolve/blob/700b3454c8baea5d308ccf06796e9e2464e7731d/packages/core/resolve-scripts/configs/schema.resolve.config.json#L234
