### ISSUE TITLE
Add .testcaferc.json to the project template

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#1004]
I have `jest.config.js` where i can configure unit tests, but no config file for testcafe. Testcafe params are specified in `run.js` for some strange reason.
Testcafe uses `.testcaferc.json` https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html, so we can add this file to the new project template

**Comment by const314** [comment]
Fixed in 0.31.0
