### ISSUE TITLE
It is impossible to handle error if it is thrown in aggregate event handler

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#101]
1. Add aggregate command with event as result with type 'created'
2. Add 'created' event handler to aggregate with error that is thrown inside
3. Execute command with some aggregate id - handler is not executed because no one event is stored yet
4. Execute it again with the same aggregate id - handler is executed once with stored event

Error throwed in handler is impossible to catch wrapping the 'executeCommand' function by try-catch construction

**Comment by VadimKhoroshiltsev** [comment]
I cannot reproduce the problem. Can you provide additional details?
