### ISSUE TITLE
Cassandra adapter and sequential execution

### ISSUE THREAD

**Issue by IhostVlad** [reimagined/resolve#1050]
**_Issue from email_**

So, I've tried to implement the cassandra storage adapter and I'm running into an issue. It looks like the write model is not being updated correctly.
 
In my load-events.js file I'm doing this:
```js
const loadEvents = async ({ client, tableName }, filter, callback) => {
  const { eventTypes, aggregateIds,  startTime, finishTime } =  filter
  var select = `SELECT * FROM  ${tableName} WHERE aggregate_id IN ?`;
  var selectArgs = [aggregateIds];
  if (startTime != null) {
    console.log("startTime is not null");
    if (startTime <0) {
      select += ` AND event_timestamp > 0`;
    } else {
      select += ` AND event_timestamp > ?`;
      selectArgs.push(startTime);
    }
  }
  if (finishTime != null) {
    throw new Error("WASN'T EXPECTING FINISH TIME");
  }
  await client.execute(select, selectArgs, {  prepare : true }).then( result=> {
    result.rows.forEach(async element => {
      var retElement = {}
      retElement.type = element.event_type;
      retElement.payload = JSON.parse(element.payload);
      retElement.aggregateId = element.aggregate_id;
      retElement.aggregateVersion = element.aggregate_version.toInt();
      retElement.timestamp = element.event_timestamp.toNumber();
 
      console.log(retElement);
 
      await callback(retElement);
    });
  });
}

export default loadEvents
````
 
This method seems to be returning the elements correctly. My projection function is also returning the correct state.
 
```js
export default {
  Init: () => ({}),
  [PLAYER_ADDED]: (state, event) => {
    const timestamp = event.timestamp;
    const { leagueId, teamId, playerId, leagueRosters } = event.payload;
    const leagueObject = {}
    leagueObject[leagueId] = {...state[leagueId], ...leagueRosters}
    leagueObject[leagueId][playerId] = teamId;
    return {...state, ...leagueObject}
  }
}
``` 
 
What I'm seeing is that when the second event is being applied, this projection function is getting an empty object for "state". Not the object I returned when the first event was applied.
 
I've sent the same commands to an instance running the cassandra storage adapter and one running the light storage adapter. The projection function is the exact same code. The object that I'm returning from loadEvents appears to be returning the exact same object from both storage adapters but for some reason state isn't being updated correctly.
 
Any ideas what I could be doing wrong? What other information can I provide to you that would help debug this? Is there a way I could debug this?

**Comment by IhostVlad** [comment]
Showed `loadEvents` functions looks to be correct, but in fact it works wrong, since every next event is being applied then previous event has not applied.

This construction does not intent to wait events, since Promises generated in `forEach` are not being waited and not queued sequentially 
```js
  await client.execute(select, selectArgs, {  prepare : true }).then( result=> {
    result.rows.forEach(async element => {
```

Corrent version is
```js
const result = await client.execute(select, selectArgs, {  prepare : true })
for(const row of result.rows) {
  const retElement = {}
  retElement.type = element.event_type;
  retElement.payload = JSON.parse(element.payload);
  retElement.aggregateId = element.aggregate_id;
  retElement.aggregateVersion = element.aggregate_version.toInt();
  retElement.timestamp = element.event_timestamp.toNumber();
   await callback(retElement);
}
```

**Comment by drcca** [comment]
This seems to work. I'm still curious about why I'm being passed in a startTime of -2. Clearly that's the beginning state of event playback but is that a magic constant somewhere in the code?

**Comment by IhostVlad** [comment]
@drcca There is no any magic constant with value `-2`. This value is calculation result from expression `-2=(-1) + (-1)`, where first `-1` is flag for position before the beginning of the time and second `-1` is amendment for `$gt` semantics.
When `loadEvents` method is invoked in any storage adapter, it's supposed that retrieved events should have timestamp strictly greater than provided `startTime`, so core packages like `resolve-command` or `resolve-query` decreases timestamp by one to reload current timeframe.
Also `-1` is constant in `resolve-command` and `resolve-query` packages to mark before-the-beginning-of-time state (https://github.com/reimagined/resolve/blob/master/packages/core/resolve-command/src/index.js#L47 , https://github.com/reimagined/resolve/blob/master/packages/core/resolve-query/src/wrap_view_model.js#L28 )

**Comment by superroma** [comment]
This looks bad, you can make everything explicit, why these magic constants?
You could just tell the adapter what you want without magic and assumptions.
