### ISSUE TITLE
eventBroker Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1081]
**Describe the bug**
node:40408) UnhandledPromiseRejectionWarning: Error: SQLITE_CANTOPEN: unable to open database file
(node:40408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Server is still loading - please wait...
Error while transmitting events for listener TypeError: Cannot read property 'getListenerInfo' of undefined

**To Reproduce**
Remove eventBroker section, delete Data folder.

**Expected behavior**
Validation or error related to the eventBroker

**Comment by IhostVlad** [comment]
Fixed in reSolve version 0.20.6 ( https://github.com/reimagined/resolve/commit/30a37a3f0ed3ceb2b09e8f613917638029fbe848 )
Issue about default data folder is #1082
