### ISSUE TITLE
Yarn dev process does not stop after first first ctrl+c

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1096]
Use brewcomputer app and branch "resolve-update" as an example
Run yarn.
Run yarn dev. The app will start. 
Then press ctrl+c to stop the process. See the following message in the console:
$ SIGINT
But the app still works. Press ctrl+c second time. The app will stop.

**Expected behavior**
To stop the app and its processes after first ctrl+c

**Comment by MrCheater** [comment]
Can't reproduce the issue
![shplist](https://user-images.githubusercontent.com/5055654/58161145-65fd3400-7c88-11e9-818a-a4df3fcd8073.png)

**Comment by IhostVlad** [comment]
In fact resolve application and it's satellite processes (broker, etc) perform shutdown after pressing `Ctrl+C` first time.
But there is OS terminal issue that shell prompt had been shown before all application-dependent I/O has been finished, so there is no way no fix this issue *

You can create simple node.js project with two files    
**package.json**     
```js
{
  "name": "console-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  }
}
```

**index.js**    
```js
const main = async () => {
  while(true) {
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('WORK')
  }
}

process.on('SIGINT', () => {
  console.log('EXIT')
  process.exit(0)
})

main()
```

And then run this project via two different ways: directly invoke `node index.js` in shell, and invoke `yarn start` in shell. In first case you will see `EXIT` message and then prompt shell. In second case you will see prompt shell and `EXIT` message later, which causes effect with non-terminated app, however It had been already exited.



* - Of course it's possible to solve issue via platform-dependent low-level manipulations with OS terminal process, but it is not reSolve framework issue anyway.
