### ISSUE TITLE
read-model tester should have simple example and documentation.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1098]
At the moment it is quite difficult to figure out how to use read-model tester according to the examples in the repository. There should be a simple example like

here are your events
`const events = [...]`

here is your adapter, which you should initialize each test

and here is your test, where projection and resolvers are from your app.
```
  test(`fermentables`, async () => {
    expect(
      await givenEvents(events)
        .readModel({
          name: 'Ingredients',
          projection,
          resolvers,
          adapter
        })
        .fermentables({})
    ).toMatchSnapshot(`fermentables`)
  })
```

**Comment by MrCheater** [comment]
Scheduled for release on May, 15
