### ISSUE TITLE
executeCommand became slower on the local run after V0.19 to V0.20.5 upgrade

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1102]
We have a simple script to import data via API handler. In the API handler, we do executeCommand. And access the API handler via fetch like this
```
await fetch(`${origin}/api/import-data`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${JWT}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ type, data })
  })
```
V0.19
<img width="508" alt="Screenshot 2019-05-22 at 13 20 42" src="https://user-images.githubusercontent.com/5825789/58167368-7e734b80-7c94-11e9-88c9-4cf905f1352d.png">
V0.20.5
<img width="629" alt="Screenshot 2019-05-22 at 13 21 38" src="https://user-images.githubusercontent.com/5825789/58167415-96e36600-7c94-11e9-85e3-9d5dfb7d8a77.png">

**Comment by IhostVlad** [comment]
Closing due inactivity and major reSolve architecture changes. If you still having performance problems, open new issue with describing desired performance values.
