### ISSUE TITLE
resolve-storage-mysql adapter performance fail V0.19 to V0.20.5 upgrade

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1103]
We have a simple script to import data via API handler. In the API handler, we do executeCommand. And access the API handler via fetch without any magic.
```
await fetch(`${origin}/api/import-data`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${JWT}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ type, data })
  })
```
We configured the application to use resolve-storage-mysql adapter. A tested on v 0.19, it takes about 12 secs.
<img width="675" alt="Screenshot 2019-05-22 at 15 54 28" src="https://user-images.githubusercontent.com/5825789/58175958-f7c96900-7ca9-11e9-9cc4-e4e334a36fcf.png">

Then we tested same code on the v 0.20
<img width="615" alt="Screenshot 2019-05-22 at 15 29 01" src="https://user-images.githubusercontent.com/5825789/58176004-0dd72980-7caa-11e9-9d7c-8577646572a2.png">

It looks like a performance issue.

**Comment by krutilin** [comment]
It is not a mysql issue. Here are logs from 19 and 20 version.
[mysql Log 20.log](https://github.com/reimagined/resolve/files/3211156/mysql.Log.20.log)
[mysql Log 19.log](https://github.com/reimagined/resolve/files/3211157/mysql.Log.19.log)

**Comment by IhostVlad** [comment]
Closing due inactivity and major reSolve architecture changes. If you still having performance problems, open new issue with describing desired performance values.
