### ISSUE TITLE
Code reuse between react & react-native / Using react-native-web with resolve

### ISSUE THREAD

**Issue by bartekus** [reimagined/resolve#1113]
Whats the best way to go about implementing react-native-web and resolve in such way that the code can be share between web and mobile.
This [example](https://github.com/bartekus/reactuate-app) outlines the concept of what I'm describing. But to summarize, both web and mobile access the same component files in a monorepo setup.

In general it would be amazing to be able implement resolve on the existing create-react-app/create-react-native-app projects without ejecting, especially given that it is webpack based/centric.

**Comment by MrCheater** [comment]
You can see how ReSolve, Web and React Native work together in the "shopping-list-advanced" example.

* The folder "web" contains a regular ReSolve Web application. (https://github.com/reimagined/resolve/tree/master/examples/shopping-list-advanced/web)

* The folder "native" contains a regular React Native application. (https://github.com/reimagined/resolve/tree/master/examples/shopping-list-advanced/native)

* The folder "ui" contains reusable user interface components that are used in Web and React Native(https://github.com/reimagined/resolve/tree/master/examples/shopping-list-advanced/ui/src)

This is an experimental example and maybe it will be changed in the future.

Now the ReSolve doesn't support the create-react-app / create-react-native-app projects without ejecting. We plan to think about it in the future.
