### ISSUE TITLE
Add warning about conflict ConnectionStringFormat.database and options.databaseName in resolve-readmodel-mongo

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#1124]
Connection String Format

> mongodb://[username:password@]host1[:port1][,...hostN[:portN]]][/[**database**][?options]]

Adapter Options
```
options: {
  databaseName: '...'
}
```

**Comment by Lykoi18** [comment]
Fixed in version 0.20.24 https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d10-1f008d7350fe8d69004346e1aaa331b5/views/imgo https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d8-44f8ef114a6f8f083ef6117665c2074a/views/imgo
