### ISSUE TITLE
Resolver responding with inconsistent state if read-model update failed

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1126]
Resolver is still responding with 200 OK status and inconsistent state if read-model update failed

**Comment by superroma** [comment]
Why it is a problem? Resolver returns a read model content and doesn't care how it got there, update fail might not be a critical thing. Single user might have a problem, this is not a reason to stop serve others. 
If you need such behavior, you can code it yourself, have a flag somewhere that update has failed and throw an error in resolver if this flag is set.

**Comment by alexslavr** [comment]
Is it possible to check the read-model status in resolver?
