### ISSUE TITLE
How to manage jwt in the sagas

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1132]
We need some example in docs, how to manage jwt in sagas. Should it be a special 'system robot' jwt or we must handle user jwt somehow.

And there must be some code samples related to this topic too.

**Comment by superroma** [comment]
Saga is not related to any user, it is some kind of robot user. 
So it should have a "system" or its own JWT token. Server code has access to the required keys, so you can construct any token you need, and check for it in the command handler code.

**Comment by MrCheater** [comment]
Sample "saga-with-authorization" 
https://github.com/reimagined/resolve/tree/master/tests#saga-with-authorization
