### ISSUE TITLE
How to validate aggregate Id from client on create command?

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1139]
At the moment we generate aggregate id and send it from a client on the create command.
See Shopping List example:
https://github.com/reimagined/resolve/blob/master/examples/shopping-list/client/components/ShoppingListCreator.js#L24

I discussed this with developers:
pros
The user creates id and it could be a meaningful value for navigation or something else.
Theoretically, it is just a string and should not break anything.

cons
In practice, we can send a huge string as id and broke app navigation.
<del>We have no place where to put validation for aggregate id on the server side.</del>(update we can validate it in the command handler. Maybe need some docs on how to do.)

**Comment by superroma** [comment]
Something like this:
```js
const withAggregateIdValidation = commandHandler => (state, event, ...rest ) => {
    if (event.aggregateId.length > 255)
        throw new Exception('aggregateId is too long')
    return commandHandler(state, event, ...rest)
}
...
createShoppingList: withAggregateIdValidation((state, { payload: { name } }) => {
    if (state.createdAt) {
      throw new Error('Shopping List already exists')
    }
    if (!name) {
      throw new Error(`The "name" field is required`)
    }

    return {
      type: SHOPPING_LIST_CREATED,
      payload: { name }
    }
  }),
```

**Comment by superroma** [comment]
Another approach - use command validators. It has a benefit that you can use command validators on the client before sending a command:
```js
const compose = (...fns) => x => fns.reduceRight((y, f) => f(y), x)

const checkIdNotNull = command => {
  if (!command.aggregateId) {
    throw new Error('aggregateId is null')
  }
  return command
}
const checkIdTooLong = command => {
  if (command.aggregateId && command.aggregateId.length > 10) {
    throw new Error('aggregateId is too long')
  }
  return command
}

const withCommandValidator = validator => commandHandler => (
  store,
  command,
  ...rest
) => commandHandler(store, validator(command), ...rest)

const createShoppingList = withCommandValidator(
  compose(
    checkIdNotNull,
    checkIdTooLong
  )
)((state, { payload: { name } }) => {
  if (state.createdAt) {
    throw new Error('Shopping List already exists')
  }
  if (!name) {
    throw new Error(`The "name" field is required`)
  }

  return {
    type: 'SHOPPING_LIST_CREATED',
    payload: { name }
  }
})
```

**Comment by oliversturm** [comment]
I like the validation ideas, but if this is really true:

> we can send a huge string as id and broke app navigation

then I think we should probably make this specific check a default somehow.

**Comment by krutilin** [comment]
@oliversturm default checks will be another one "magic" for the developer. Possibility to validate and notes about it in the docs more than enough.

**Comment by superroma** [comment]
> I like the validation ideas, but if this is really true:
> 
> > we can send a huge string as id and broke app navigation
> 
> then I think we should probably make this specific check a default somehow.

Yes, I missed this part. But really, as @krutilin said, it should be a part of another layer - some infrastracture that makes sure these validation are called in all appropriate places. 
Currently it is easy to forget to check JWT or validate ids, sanitize input and things like this. 

@krutilin I suggest you start doing these things in your app, so we can better understand what we need to change in reSove to make it possible.

**Comment by oliversturm** [comment]
@krutilin My point was that if a certain missing validation is possibly going to break our system, then we shouldn't regard it optional. Implementing it is no more magic than the rest of the framework.

**Comment by superroma** [comment]
@oliversturm, in this particular case, i can say that we have nearest plans to decouple routing (and frankly the whole React) from the reSolve core, so it would be out of its scope. 

And yet we have plans to implement several reusable modules that would require validation of assumptions, so the have to rely on some common infrastructure for validation and security. 

So I see this as another layer that protects average developer from mistakes by having opinion on how to do things.
