### ISSUE TITLE
Suggestion: "Add DEBUG=resolve* DEBUG_LEVEL=error" to the dev run in the examples and docs.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1144]
It is quite difficult to debug resolve applications, for example, you wrote a saga and added some code that fails sometimes. And your unit tests do not catch it. The app will still start, looks normal, but events will stop applying. Your console will be without errors until you add "Add DEBUG=resolve* DEBUG_LEVEL=error" and receive:
`  resolve:resolve-runtime:local-event-broker Error while applying events to read-model`

I have a suggestion to add "Add DEBUG=resolve* DEBUG_LEVEL=error" by default to the examples.

Maybe this issue is part of a bigger and general issue or tutorial part like: 'How to debug resolve applications?'

see also:
#1101

**Comment by superroma** [comment]
Errors should be reported to console without any options. DEBUG env should be used only when you are trying to understand what system is doing

**Comment by IhostVlad** [comment]
Fixed in version 0.20.22
