### ISSUE TITLE
The default SQLite table name is a keyword of sqlite

### ISSUE THREAD

**Issue by cdnil** [reimagined/resolve#1149]
**Describe the bug**
The default table name of SQLite is `default`. https://github.com/reimagined/resolve/blob/master/packages/adapters/storage-adapters/resolve-storage-lite/src/connect.js#L4
But I found `default` word is a keyword of SQLite, https://www.sqlite.org/lang_keywords.html
It will cause a syntax error when using SQLite command line:
```
sqlite3 data/event-store.db
SQLite version 3.19.4 2017-08-18 19:28:12
Enter ".help" for usage hints.
sqlite> select * from default;
Error: near "default": syntax error
```

**To Reproduce**
> sqlite3 data/event-store.db
> select * from default;
Error: near "default": syntax error

**Comment by IhostVlad** [comment]
@cdnil In resolve eventstore and read-model adapters, `default` is just default value for tables prefix, and should be provided in configuration explicitly in most cases.
Also, SQL dialects like `SQLite`/`MySQL`/etc provide support for keyword escaping, so just escape it by wrapping in backticks. Of course, resolve adapters performs such kind of wrapping automatically under the hood.
```
sqlite> CREATE TABLE `default` ( `id` VARCHAR, PRIMARY KEY(`id`) );
sqlite> INSERT INTO `default`(`id`) VALUES ("AAA");
sqlite> INSERT INTO `default`(`id`) VALUES ("BBB");
sqlite> SELECT * FROM `default`;
AAA
BBB
```

**Comment by IhostVlad** [comment]
@cdnil Specify table name and prefixes explicitly to avoid default names.
For eventstore adapters: https://github.com/reimagined/resolve/blob/master/examples/hello-world/config.dev.js#L63-L89
For read-model adapters: https://github.com/reimagined/resolve/blob/master/examples/hello-world/config.dev.js#L15-L41

**Comment by cdnil** [comment]
@IhostVlad Thank you for your great answers. There are very helpful.
