### ISSUE TITLE
It is hard to debug in cloud using logs

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#1151]
Some log messages are splitted on multiple lines in CloudWatch logs. Necessary to find a way to have minimalistic logs, especially for errors and JSON logging. Example:
https://github.com/reimagined/resolve/blob/dev/packages/core/resolve-runtime/src/cloud/lambda-worker.js#L14:
![image](https://user-images.githubusercontent.com/20209954/60583263-2ea79a00-9d93-11e9-81f7-e6722a8e8534.png)

**Comment by MrCheater** [comment]
Fixed in version 0.20.23
