### ISSUE TITLE
kafka as eventBroker?

### ISSUE THREAD

**Issue by rahul33** [reimagined/resolve#1154]
Is it possible to easily replace zmq with kafka to serve as the event broker? 

...
eventBroker["launchBroker"] = true;
eventBroker["zmqBrokerAddress"] = "tcp://127.0.0.1:3500";
eventBroker["zmqConsumerAddress"] = "tcp://127.0.0.1:3501";
...

Please advise, Thanks!

**Comment by MrCheater** [comment]
The event broker is a messaging service (zmq) and a database with metadata (sqlite).
A messaging service must meet the following criteria:
1) FIFO - Each message is read by just one receiver
2) Guaranteed messaging with XPUB/XSUB pattern support

You can fork package ["resolve-local-event-broker"](https://github.com/reimagined/resolve/tree/master/packages/core/resolve-local-event-broker) and replace zmq with any other messaging service that matches the criteria.

**Comment by rahul33** [comment]
Perfect! thanks for this info
