### ISSUE TITLE
Allow config to skip UI

### ISSUE THREAD

**Issue by Iodine-** [reimagined/resolve#1183]
I appreciate the out-of-the-box convenience of having and e2e micro service spun up when creating a new reSolve project; however, I am finding it frustrating when I have no need for a UI that when running `yarn run dev` it keeps having to recompile and launch a new browser tab.

I would love it if there was a simple way to configure my project to omit the UI portion of the application, and focus on the server side implementation.

I am not sure if I am just missing something - but I think reSolve adds a ton of value in its own right just in its server side implementation, and the UI support with CRA and view-models is another level of functionality that is going to be specific to each use case.  It would be valuable to decouple the two and make it easy to configure when to use which.

**Comment by IhostVlad** [comment]
Now there is no simple out-of-the-box opportunity for a separate assembly of the server and client parts. ReSolve development roadmap implies a significant separation of the backend and the UI in future versions.

However, event right now you can tune the application building. The `run.js` entry point determines which `resolve-scripts` tools will be invoked for the appropriate build mode. For many aspects of the assembly, it is possible to modify them through arguments or environment variables. Opening browser can be disabled via [appropriate environment variable](https://github.com/reimagined/resolve/blob/master/examples/hacker-news/run.js#L163) setting.  Client bundle can be eliminated to empty entity via [advanced webpack configuration](https://github.com/reimagined/resolve/blob/master/examples/shopping-list-advanced/web/run.js#L51-L62).

By the way, invoking [build mode](https://github.com/reimagined/resolve/blob/master/packages/core/resolve-scripts/src/build_mode.js#L12) with custom [adjust webpack function](https://github.com/reimagined/resolve/blob/master/examples/with-postcss/config.adjust_webpack.js) can give you significant control over application building, including custom runner process.
