### ISSUE TITLE
Example of alternative interface other than HTTP

### ISSUE THREAD

**Issue by Iodine-** [reimagined/resolve#1184]
I am hoping to figure out a way to interface with my reSolve service from a local queue worker, rather than having events posted to an API endpoint. 

For example, if I wanted to have a worker consuming messages from an SQS queue - Ideally I would not need to then make an HTTP requests to get that event ingested.  I would much rather simply be able to issue commands to aggregates from the worker.  I originally thought a custom module may be a possible route - but the documentation in that area is pretty sparse.

Would love some guidance on an alternative to posting commands to an HTTP endpoint, and instead issuing them directly from a worker.  

Even exposing the underlying express server in some way, ideally with access to the bootstrapped `resolve` instance.  Right now it seems the express server is a black box.

**Comment by MrCheater** [comment]
> Would love some guidance on an alternative to posting commands to an HTTP endpoint, and instead issuing them directly from a worker.

You can write a custom HTTP wrapper for Commands and Queries using this API: https://reimagined.github.io/resolve/docs/curl

We do not provide access to the express server for compatibility with Resolve Cloud and AWS Lambda

**Comment by Iodine-** [comment]
Thanks for the information @MrCheater.  Wrapping the HTTP endpoint does not really get away from the fact that it is still going to ultimately post events over http, Perhaps it was not clear, but I was hoping there would be some way in which a worker ingesting events from a queue may be able to directly call `resolve.executeCommand()`.   

> We do not provide access to the express server for compatibility with Resolve Cloud and AWS Lambda

Are those 2 use cases the main target audience for reSolve?  It seems a shame to have such good structure and tooling supporting ES/CQRS in node, but limiting how it can be used due to the need to be compatible with a specific host.  I appreciate reSolve is likely something you guys make available as you build it out for a particular use case.   I just wanted to share that as it has a very appealing foundation (aggregates, reducers, projections, sagas, adapters etc...) that make it very nice to get in an working with, it is unfortunate to then start to realize its not so simple to just get kettle (ES/CQRS infrastructure), without getting the kitchen sink.  eg - I think down the road, making things more modular would really expand the value proposition reSolve could offer.  If i don't care about deploying to lambda, or reSolve cloud - why is the underlying server still black boxed? It's certainly a concern when considering reSolve, that we have to be okay with some things being out of out control.

You also mentioned reSolve Cloud, and lambda - is there some documentation surrounding that?  I see home links in the GitHub `/docs/README.md` file, but they don't seem to point to anything specific.

**Comment by superroma** [comment]
Hi @Iodine- 
Resolve-cloud portion of framework is not ready for production yet.
And I understand that without it, hiding some express features looks strange. 

We need to find a balance between hiding non-compatible features and giving power to developers. We will provide a way to access all platform features that you need.

Regarding being modular - we do have modules https://github.com/reimagined/resolve/tree/master/packages/core that were intended to be used independently, but frankly we never had much interest in them, so currently I'm not even sure that https://github.com/reimagined/resolve/tree/master/packages/core/resolve-command that I would suggest you to use, works as described. We'll check and get back to you.

**Comment by IhostVlad** [comment]
@Iodine-  You can issue an command via `resolve-command` package. Use following code snippet. Of course, you should have credentials for access event store in adapter.


```js
const es6Import = moduleName => require(moduleName).default
const createStorageLiteAdapter = es6Import('resolve-storage-lite')
const createCommandExecutor = es6Import('resolve-command')
const createES = es6Import('resolve-es')

const main = async () => {
  const memoryStorage = createStorageLiteAdapter({ databaseFile: ':memory:' })
  const eventStore = createES({ storage: memoryStorage })

  const aggregates = [{
    name: 'my-aggregate',
    commands: {
      myCommand: (state, { payload: { a, b, c } }) => ({
        type: 'EVENT_TYPE',
        payload: { a, b, c }
      })
    }
  }]

  const executeCommand = createCommandExecutor({
    eventStore,
    aggregates
  })

  const event = await executeCommand({
    aggregateId: 'aggregate-id',
    aggregateName: 'my-aggregate',
    type: 'myCommand',
    payload: {
      a: 'aaa',
      b: 'bbb',
      c: 'ccc'
    }
  })

  console.log(event)
}

main()
```

**Comment by Iodine-** [comment]
Thanks for the response guys.  When you mentioned `resolve-cloud` I did some searching around the intertubes for some more information, but as you indicated, seems there isn't much available yet!  And as you indicated, that definitely makes it hard to explain why some things are the way they are.

I did briefly take a look at some of the core packages to see about using them directly as @IhostVlad  has suggested - I got discouraged as I was assuming since reSolve was already bootstrapping things like the storage adapters and eventstore, I could just reuse those instead of having to create new ones in my particular module.  But I will definitely put some more time into investigating that.

I appreciate things are still being worked on, and you all have been extremely responsive and helpful,  I wonder if you guys have considered a slack channel for less formal questions?   Also keeping the docs up to date (especially confusing because of the `docs` branches in the repo, docs site, and examples all seem to be in different stages of development) will help!  I think at some point down the road, a few different starter templates would be fantastic - you already have the kitchen sink option, as things become more flexible - I would love to see a few other options of various levels of complexity.

Thanks again team, really appreciate the discussion

**Comment by superroma** [comment]
> I wonder if you guys have considered a slack channel for less formal questions?

We are not using Slack internally. 
Don't hesitate to ask any question here or on [stackoverflow](https://stackoverflow.com/questions/ask?tags=resolvejs).
