### ISSUE TITLE
View model crash on DISCONNECT_VIEWMODEL

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1195]
It is reproducible on the resolve admin app. Try to open
https://admin.resolve.sh/app/your-app/performance tab. Then go and prepare some coffee. Back to your computer and try to press "refresh" stats button. You will receive:
![image](https://user-images.githubusercontent.com/5825789/63758493-86124400-c8c4-11e9-8250-24c7646c8ada.png)

I got the same stack with the brewcomputer app. Looks like the problem is common for all resolve apps.

**Comment by MrCheater** [comment]
See also: _[link to an internal issue tracker removed by maintainer]_

**Comment by krutilin** [comment]
https://github.com/reimagined/resolve/blob/master/packages/core/resolve-redux/src/create_view_models_reducer.js
see
LOAD_VIEWMODEL_STATE_SUCCESS
LOAD_VIEWMODEL_STATE_FAILURE
and DISCONNECT_VIEWMODEL

on success, you adding viewModelName field to the state object, but on the failure, you don't. On disconnect, you trying to access it anyway.

**Comment by MrCheater** [comment]
Fixed in version 0.25.0
