### ISSUE TITLE
Eventstore metadata

### ISSUE THREAD

**Issue by davidnussio** [reimagined/resolve#1214]
I looked into the eventSource package to found out if there is a way to save metadata with event, but it seem not possible.

There are some use case where save event with some extra metadata information are very helpful.

For instance, save user information for legal purposes or save the version of the software that recorded the event so that you can easily reconstruct a version of the software with its data at some point in the past.

Do you have any suggestions?

Thank you, good jobs!
David

**Comment by superroma** [comment]
Hi David, 

When discussing event schema, we decided to put everything that is application-specific under "payload" key, and keep essential properties for event store to work at the top level. Essential properties are mapped to specific database fields with known formats and indexes.

Payload, in turn can contain any kind of meta information or some kind of envelop that is processed by your app. 

So the easiest solution is to keep metadata in the payload. Then you can use function similar to this one to return event:
```
const createEvent(jwt, {type, payload}) => {
    type,
    payload: {
        _metadata: { jwt },
       ...payload 
    }
}
```

If you want metadata to be hidden from the app, then, I guess it is not that easy and we'll need to modify eventStore code (this way metadata would need its own column in the database).

**Comment by davidnussio** [comment]
Thanks for the reply and for the proposed solution.
I used the metadata in Axon Framework 3.0 and they were saved in separate columns.
However, I think your solution might be ok.

I can _filter_ the metadata field in the projections and I can use it in the admin display models.
