### ISSUE TITLE
--stop-on-first-fail option for test cafe under the hood in the resolve-scripts

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1227]
resolve-scripts modify default test-cafe behavior, by adding additional --stop-on-first-fail option in the resolve scripts. And there is no way to override it for the customer's side.
https://github.com/reimagined/resolve/blob/b362f6c2dd78758540af1d5ba50519617cf996bb/packages/core/resolve-scripts/src/run_testcafe.js#L125

**Comment by MrCheater** [comment]
Fixed in version 0.21.12
