### ISSUE TITLE
Using with gRPC or Rabbitmq

### ISSUE THREAD

**Issue by danielsalles** [reimagined/resolve#1253]
Hello, I would like to use your framework. But without the HTTP call, for that I would like to use gRPC or Rabbitmq to perform the commands or queries. Can you tell me how to best use this? And it was also unclear how your messagebus works, do you use any external services?

**Comment by superroma** [comment]
Hi, there are currently two implementations of reSolve "engine" - local - node.js app based on Express, and cloud - an upcoming serverless implementation based  on AWS.
Local engine is using Express, and ZeroMQ as a message bus.

As I understand, Express supports gRPC, so in theory it is possible to have gRPC endpoints. We will check and post results here.

**Comment by danielsalles** [comment]
Thanks @superroma  for your response. But I think I expressed myself badly.
For context, I want to use resolve as microservices. Each context is a project, but like every project at times I will need to access other contexts, and to make this connection I want to use gRPC at some times, and at other times I want to use rabbitmq, if I need consistency.

**Comment by MrCheater** [comment]
We have implemented an example that uses gPRC to send commands:
https://git.io/JeSiY
