### ISSUE TITLE
Can't deploy shopping-list-advanced to the cloud

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1257]
**Describe the bug**
Can't deploy shopping-list-advanced to the cloud out of the box.

**To Reproduce**
Add 
`"cloud": "cd web && node ./run.js cloud", `
to the root package.json
Then run yarn resolve-cloud to deploy.

Recieve

start deploying the "shopping-list-advanced" application to the cloud                                                                                                   14:40:58
 ERROR  fs.js:114                                                                                                                                                       14:41:26
 ERROR      throw err;                                                                                                                                                  14:41:26
 ERROR      ^                                                                                                                                                           14:41:26
 ERROR  Error: ENOENT: no such file or directory, open '/Users/youruser/Desktop/shopping-list-advanced/web/dist/common/cloud-entry/package.json' 

**Additional context**
There are parts of the cloud definitions in this demo, it looks like it should be able to deploy it out of the box.

**Comment by Lykoi18** [comment]
Fixed in version 0.22.6
