### ISSUE TITLE
The data import does not work in the application created by the hacker-news sample.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1280]
1. Execute the command in order to create a new application:
npx create-resolve-app resolve-example -e hacker-news
2. Start the just create application.
3. Try to import data by the command:
npm run import

The following result is obtained:

aleksei.matosov@Matosov-MacBook resolve-example % npm run import

> resolve-example@0.21.8 import /Users/aleksei.matosov/Projects/resolve-example
> babel-node ./run.js import

[ Shared client ESM chunks ] Time: 4262ms
Built at: 12/26/2019 14:40:54
[ Client IIFE entries ] Time: 4915ms
Built at: 12/26/2019 14:40:55
[ Server local entry point, local bus broker ] Time: 2245ms
Built at: 12/26/2019 14:40:52
[ Shared server ESM chunks ] Time: 796ms
Built at: 12/26/2019 14:40:51
[ Server CommonJS entries ] Time: 3837ms
Built at: 12/26/2019 14:40:54
Access error: GET "/api/reset-domain" is not addressable by current executor
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resolve-example@0.21.8 import: `babel-node ./run.js import`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resolve-example@0.21.8 import script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aleksei.matosov/.npm/_logs/2019-12-26T12_40_55_758Z-debug.log
aleksei.matosov@Matosov-MacBook resolve-example %

**Comment by MrCheater** [comment]
Additional context:
```
~$ npx create-resolve-app@0.21.11 hn3 -e hacker-news

Creating hn3 in ./hn3 based on hacker-news example

Load example

Patch package.json

Install dependencies
yarn install v1.21.1
info No lockfile found.

success Saved lockfile.
Done in 36.76s.

Success! hn3 is created 

Happy coding!

~$ cd hn3
~/hn3$ yarn run import

yarn run v1.21.1
$ babel-node ./run.js import
[ Shared client ESM chunks ] Time: 2709ms
Built at: 2019-12-27 1:18:39 PM
[ Client IIFE entries ] Time: 3006ms
Built at: 2019-12-27 1:18:40 PM
[ Server local entry point, local bus broker ] Time: 1565ms
Built at: 2019-12-27 1:18:38 PM
[ Shared server ESM chunks ] Time: 690ms
Built at: 2019-12-27 1:18:37 PM
[ Server CommonJS entries ] Time: 2411ms
Built at: 2019-12-27 1:18:39 PM
Application listening on port 3000!
[ Shared client ESM chunks ] Time: 358ms
Built at: 2019-12-27 1:18:43 PM
[ Server local entry point, local bus broker ] Time: 216ms
Built at: 2019-12-27 1:18:43 PM
[ Shared server ESM chunks ] Time: 84ms
Built at: 2019-12-27 1:18:43 PM
Import has been started. Press Control+C to stop import
Application listening on port 3000!

Data importing from news.ycombinator.com [--------------------] 19/952
```
