### ISSUE TITLE
Double run 'yarn dev' leads to uninformative error

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#1287]
**Describe the bug**
If you run the app in dev mode when it is already running, you get this:
```
Access error: GET "/api/reset-domain" is not addressable by current executor
error Command failed with exit code 1.
```

**To Reproduce**
1. cd <your app>
2. yarn dev &
3. yarn dev

**Expected behavior**
A clear explanation - usually "can't bind to port 3000 - check if the app already running".

**Comment by IhostVlad** [comment]
Fixed in version 0.22.4
