### ISSUE TITLE
Unable to deploy resolve application to the cloud without aws-sdk dependencies

### ISSUE THREAD

**Issue by aleks-pro** [reimagined/resolve#1292]
To deploy resolve application to the cloud you need add `aws-sdk` and `aws-xray-sdk-core` modules to `devDependencies` even if you don't use these modules explicitly in your app.

resolve version:           0.21.13
resolve-cloud version: 0.12.0

**Comment by MrCheater** [comment]
All ReSolve examples contain `aws-sdk` and `aws-xray-sdk-core` in devDependencies

https://github.com/reimagined/resolve/blob/master/examples/cli-uploader/package.json#L47-L49

https://github.com/reimagined/resolve/blob/master/examples/hacker-news/package.json#L64-L66

https://github.com/reimagined/resolve/blob/master/examples/hello-world/package.json#L35-L37

https://github.com/reimagined/resolve/blob/master/examples/image-gallery/package.json#L40-L42

https://github.com/reimagined/resolve/blob/master/examples/shopping-list-advanced/web/package.json#L37-L39

https://github.com/reimagined/resolve/blob/master/examples/shopping-list/package.json#L44-L46

https://github.com/reimagined/resolve/blob/master/examples/with-angular/package.json#L45-L47

https://github.com/reimagined/resolve/blob/master/examples/with-postcss/package.json#L35-L37
