### ISSUE TITLE
to know what i'm getting into as a developer i'd like to see a usage example in the readme because then i can see how you use the api

### ISSUE THREAD

**Issue by bionicles** [reimagined/resolve#1293]
**Is your feature request related to a problem? Please describe.**
I visited the README and didn't see a usage example, just a link to a folder of examples, then I have to pick an example

**Describe the solution you'd like**
just a code block in the readme showing how to use it

**Describe alternatives you've considered**
digging into folders of example code

**Comment by MrCheater** [comment]
What API do you mean?
You can easily launch any example by cloning it's folder and running `yarn && yarn dev` inside it.

**Comment by MrCheater** [comment]
Notice: this issue has been closed because it has been inactive for 52 days.
You may reopen this issue if it has been closed in error.
