### ISSUE TITLE
The view model stops working after adding more than 100 events to an aggregate.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1298]
The following exception occurs after a lot of events (more than ~100) are applied to an aggregate:

resolve:resolve-runtime:command-handler Command handler failed /api/commands [Error: SQLITE_ERROR: no such table: resolveSnapshotAdapter] {
  errno: 1,
  code: 'SQLITE_ERROR'
}

The view model stops working after that for the corresponding aggregate.

Steps to reproduce:
1. Run the Shopping List sample.
2. Add a new shopping list.
3. Open the created shopping list for editing.
4. To emulate a lot of events try to edit the shopping list name a lot of times, but press the Enter key after each new symbol adding.
The above described error occurs after the events count exceeds the ~100.

OS: MacOS 10.15.3.
Browser: any.
It's reproduced both locally and in cloud.

**Comment by IhostVlad** [comment]
Fixed in version 0.22.4
