### ISSUE TITLE
Please add into the tutorial a sample regarding the client side handling for errors, raised on the server side.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1307]
The https://reimagined.github.io/resolve/docs/tutorial tutorial describes how to add the validation code into aggregate commands.
But there are no any code samples regarding the validation errors handling on the client side.

For instance we can consider the https://github.com/reimagined/resolve/blob/master/examples/shopping-list sample.
1. Modify the createList function within the https://github.com/reimagined/resolve/blob/master/examples/shopping-list/client/components/ShoppingListCreator.js file as follows:
  createList = () => {
    this.props.createShoppingList(uuid(), {
      name:
        this.state.shoppingListName
**/*
      || `Shopping List ${this.props.lists.length + 1}`
*/**
  })
    this.setState({
      shoppingListName: ''
    })
  }
in order to have a possibility to send the empty name to server side.
2. Run the application and try to create a new shopping list with the empty name.
Result:
The following aggregate validation raises an exception on the server:
https://github.com/reimagined/resolve/blob/master/examples/shopping-list/common/aggregates/shopping_list.commands.js
But the client side UI does not show any information regarding this error.

**Comment by MrCheater** [comment]
Scheduled for release on May, 15
