### ISSUE TITLE
Deployed hacker-news crashes when the performance tracer is activated

### ISSUE THREAD

**Issue by Lykoi18** [reimagined/resolve#1341]
**To Reproduce**
1. Deploy hacker-news example to the cloud
2. Activate performance tracer in admin panel
3. Reload application page

**Comment by MrCheater** [comment]
Additional context:
subsegment.addAnnotation(key, value) // Failed when value = undefined or null

**Comment by Lykoi18** [comment]
Fixed in version 0.23.0
