### ISSUE TITLE
Semantic versioning conflict validation

### ISSUE THREAD

**Issue by SergeyShurygin** [reimagined/resolve#1353]
We are using resolve-scripts 0.22, and if you run npm install  resolve-react-hooks@0.23,  npm will install it without any warning 

1. install resolve-scripts@0.22
2. install resolve-react-hooks@0.23

it will install sucessfully

**Expected behavior**
npm error that you should have resolve version 0.23 or later

**Desktop (please complete the following information):**
 - OS: win 10

**Comment by MrCheater** [comment]
We are not the maintainer of the npm package "resolve"
https://github.com/browserify/resolve/blob/master/package.json#L75-L79

**Comment by max-vasin** [comment]
Fixed in 0.29.0
