### ISSUE TITLE
Cron sagas?

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1359]
What happened to the cron (time) sagas introduced by https://github.com/reimagined/resolve/pull/729?

I couldn't find anything about them anywhere else in the issues or docs. Why was that removed? Is there a recommendation on the best way to implement cron jobs?

**Comment by MrCheater** [comment]
Hi, @gustavopch.
Please provide a scenario when you want to schedule a cron job.
Also, you can use `sideEffects.scheduleCommand` run to create a cron job.
```
// some.saga.js

export default {
  handlers: {
    SOME_EVENT: async ({ sideEffects }, event) => {
      await sideEffects.scheduleCommand(
        event.timestamp + 1000 * 60 * 60 * 24 * 7,
        {
          aggregateName: 'SomeAggregate',
          aggregateId: event.aggregateId,
          type: 'someCommandType',
          payload: {}
        }
      )
    }
  },
  sideEffects: {
    ...
  }
}
```

**Comment by gustavopch** [comment]
@MrCheater The `scheduleCommand` function will only allow me to schedule something to happen once in the future (similar to how `setTimeout` works), but suppose I need to create a report at the end of each day (similar to how `setInterval` would work). What would be the best way to accomplish this?

**Comment by MrCheater** [comment]
You can try the following solutions:

a. Recursive scheduling
1) Command -- Event --> Saga
2) Saga schedule a command for himself

b. [API handler](https://reimagined.github.io/resolve/docs/api-handlers) + external scheduler

**Comment by gustavopch** [comment]
@MrCheater Great, thanks for pointing me in the right direction!
