### ISSUE TITLE
Adding custom css looks weird

### ISSUE THREAD

**Issue by VadimKhoroshiltsev** [reimagined/resolve#136]
```
const bundleCssSource =
    process.env.NODE_ENV === 'production'
        ? `${BASEDIR}/static/bundle.css`
        : 'http://localhost:3001/bundle.css';


<div className="app">
    <Helmet>
        <link rel="stylesheet" type="text/css" href={bundleCssSource} />
    </Helmet>
```

**Comment by IhostVlad** [comment]
Yes, code above looks few complicated, but it can be simplified by moving `bundleCssSource` constant calculation into compile-time in webpack. In particular, value of this constant is known while making bundle, so it can be substituted by Webpack DefinePlugin. Then, in `Helmet` tag just use pre-calculated variable, like `BUNDLE_CSS_SOURCE`, which capitalized due being constant value.
