### ISSUE TITLE
Let aggregates be defined within a subdomain / bounded context

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1360]
**Is your feature request related to a problem? Please describe.**
Sometimes things with the same name may have different meanings depending on their bounded contexts. For example, in an online card game, we may have the word `Card` with one meaning in the `payment` context and a completely different meaning in the `game` context. Naming is hard, but bounded contexts allow us to decide our names within a context without worrying whether that name will conflict with another part of our system.

**Describe the solution you'd like**
I would like to be able to define aggregates and read models within contexts like in the following folder structure:
```
aggregates/
  game/
    card/
  payment/
    card/
```
And the config file would be something like this:
```
aggregates: {
  game: [
    {
      name: 'Card',
      // Paths omitted for brevity...
    },
  ],
  payment: [
    {
      name: 'Card',
      // Paths omitted for brevity...
    }
  ]
]
```

**Describe alternatives you've considered**
The only alternative is to use prefixes everywhere to denote that a given name is conceptually within the context denoted by the prefix, for example:
```
aggregates/
  game-card/
  payment-card/
```
Config:
```
aggregates: [
  {
    name: 'GameCard',
    // Paths omitted for brevity...
  },
  {
    name: 'PaymentCard',
    // Paths omitted for brevity...
  }
]
```

**Additional context**
Wolkenkit, which is an event sourcing framework very similar to reSolve allows the definition of different contexts as you can read in their documentation: https://docs.wolkenkit.io/latest/reference/creating-the-write-model/defining-contexts
You can also take a look at how they implement that (note it's licensed according to AGPL v3): https://github.com/thenativeweb/wolkenkit/search?q=contextname&unscoped_q=contextname

**Comment by gustavopch** [comment]
I have thought about this issue and the prefixing alternative may actually not be that bad.

Prefixing like `GameCard` and `PaymentCard` is not great because it's a bit hard to read — it gets worse with longer names. You don't immediately see what's the prefix and what's the actual name. But I believe there's nothing stopping the usage of the following naming convention in userland:
- Aggregate: `game.Card`, Command: `game.createCard`, Event: `game.cardCreated`
- Aggregate: `payment.Card`, Command: `payment.createCard`, Event: `payment.cardCreated`

Now that seems **so** obvious :laughing:.

**Comment by timbset** [comment]
Thank you for your suggestion. We will take it into account.
