### ISSUE TITLE
Let command handlers receive an array of functions for better composability

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1362]
**Is your feature request related to a problem? Please describe.**
We frequently need to perform similar checks and validations on different command handlers.

**Describe the solution you'd like**
Currently, each handler must be a single function. I would like to be able to pass an array of functions in order to have the following usage:
```js
export default {
  createShoppingList: [
    // Ensure the user is an admin
    ifHasRole('admin'),

    // Ensure the aggregate has a null state and thus doesn't exist yet
    ifNotExists(),

    // Ensure the command payload is valid according to the JSON schema
    ifValidPayload(schema),

    // Now handle the command and return the event
    async (state, command) => {
      return {
        type: SHOPPING_LIST_CREATED,
        payload: { name: command.payload.name }
      }
    }
  ]
}
```

**Describe alternatives you've considered**
Currently, I think there are three alternatives:

1 - Just use assertion functions inside the handler (downside is that it's more verbose as you need to explicitly pass parameters around :confused:):
```js
export default {
  createShoppingList: async (state, command, jwtToken) => {
    assertHasRole('admin', jwtToken)

    assertNotExists(state)

    assertValidPayload(schema, command)

    return {
      type: SHOPPING_LIST_CREATED,
      payload: { name: command.payload.name }
    }
  }
}
```

2 - Wrap with higher order functions (downside is that things gets too nested :confused:):
```js
export default {
  createShoppingList: ifHasRole(
    'admin',
    ifNotExists(
      ifValidPayload(
        schema,
        async (state, command, jwtToken) => {
          return {
            type: SHOPPING_LIST_CREATED,
            payload: { name: command.payload.name }
          }
        }
      )
  }
}
```

3 - Create some sort of `pipe` or `compose` util or get it from some library in userland. Not terrible, but if you think that syntax is useful, why not provide it out of the box?

**Additional context**
None.

**Comment by gustavopch** [comment]
I've written the following code in userland and it seems to do the job, but I haven't unit tested it yet:
```js
export const composeHandlers = handlers => {
  return async (...args) => {
    // Run handlers sequentially
    for (const handler of handlers) {
      const result = await handler(...args)

      // If the handler produced a result, return it and end the execution
      if (result) {
        return result
      }
    }
  }
}
```

Usage in userland:
```js
export default {
  createShoppingList: composeHandlers([
    ifNotExists(),

    (state, { payload }) => {
      return {
        type: SHOPPING_LIST_CREATED,
        payload: {
          name: payload.name,
        },
      }
    },
  ]),
}
```

I believe it's just a matter of internalizing that `composeHandlers` function and use it in case we detect that the handler is actually an array instead of a function.

**Comment by timbset** [comment]
@gustavopch , thank you for the suggestion. Currently, we have no plans to support additional types of command handlers. A single-function handler is a universal solution that covers most use-case scenarios, and you can build upon it to achieve any required structure. The code you posted above is an awesome example of how you can implement a more complex scenario on your application’s side.

**Comment by gustavopch** [comment]
@timbset Thanks for the answer. I brought the idea from Wolkenkit v3: https://docs.wolkenkit.io/3.1.0/reference/creating-the-write-model/using-command-middleware/. It could be useful to have those "middlewares" in the command handlers. But indeed that's a minor convenience and it can easily be done on the application's side.
