### ISSUE TITLE
Convert reSolve's codebase to TypeScript

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1363]
**Is your feature request related to a problem? Please describe.**
I met reSolve a few days ago and I think I'm in love with it due to how easy one can build an application focusing so much on the domain and business instead of infrastructure :smile:. This is not a promise, but at the time of writing I believe I may become an active contributor. OK, that said, I believe it would be beneficial to convert the codebase to TypeScript for the following reasons:

1. **Types are a great way to document the code**. It's so much easier to understand the shape of data being passed around. That's especially helpful for new contributors like me.
2. **A lot of bugs and typos can be detected by the editor as soon as they emerge**.
3. **Refactoring is easier** because `tsc --noEmit` will give you a pretty good list of things that you broke.
4. TypeScript is becoming more and more used. By writing reSolve in TypeScript, we can **provide the best type definitions possible**. They will not only be better but also guaranteed to not get out of sync with the actual code.
5. **Editor tooling / IntelliSense / Ctrl+Space gets so much better**. That's useful for everybody: for reSolve contributors, for reSolve users that are writing in TypeScript and also for reSolve users that are writing in JavaScript (because the editors will use type definitions to improve the experience under the hood anyway).

**Describe the solution you'd like**
I'd like to know whether you would accept PRs converting the code to TypeScript.

**Describe alternatives you've considered**
There's Flow, but it not near as popular as TypeScript.

**Additional context**
- According to The State of JavaScript, TypeScript getting more popular and loved year after year: https://2019.stateofjs.com/javascript-flavors/typescript
- TypeScript is also rising interest year after year according to Google Trends: https://trends.google.com/trends/explore?cat=31&date=2012-03-19%202020-04-19&q=typescript

**Comment by MrCheater** [comment]
@gustavopch ,Thanks for the suggestion! Large JavaScript frameworks need type information for scalability and maintainability. Our numerous JavaScript packages are no exception. It’s no secret that type systems can avoid bugs and help engineers more easily navigate codebases.

Feel free to open a PR mentioning the package name you're migrating, to avoid that two people work on the same subject.
