### ISSUE TITLE
Refactor the codebase to use named exports

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1364]
**Is your feature request related to a problem? Please describe.**
Default exports are prone to generate discrepancies on how something is named where it's implemented and how it's named where it's consumed. For example:

```js
// create-foo.js
const createFoo = () => { ... }

export default createFoo
```
```js
// main.js
import makeFoo from './create-foo' // Ops... importing with a different name, likely a mistake left from some refactoring :(
```

Why is that bad? Mostly because **if you try to perform a project-wide search for `createFoo` within your editor you will possibly miss some relevant results**.

On the other hand, named exports will force you to have consistent names:

```js
// create-foo.js
export const createFoo = () => { ... }

// Bonus: no need for a second line here specifically to export what was
// declared above. The declaration and export are done together without
// losing the ability to declare the name of the function. :)
```
```js
// main.js
import { createFoo } from './create-foo' // Consistent name :)
```

If you really want to import with a different name, you'll have to be explicit about it and still the search results will include the file where you're renaming the import:

```js
// main.js
import { createFoo as makeFoo } from './create-foo' // This line will be in the results :)
```

**Describe the solution you'd like**
I believe the code should be refactored to replace default exports by named exports and that preference should be included in https://reimagined.github.io/resolve/docs/contributing#code-style.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by MrCheater** [comment]
Thank you for your suggestion. Unfortunately, after carefully reviewing your suggestion we, the ReSolve team members, came to the conclusion is no need to perform refactoring to replace default exports by named exports. Of course this is not the final word. If you think, that we did wrong then please re-create a issue.

**Comment by gustavopch** [comment]
No problem, I understand, thanks for the answer.
