### ISSUE TITLE
Create roadmap and start documenting releases

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1365]
**Is your feature request related to a problem? Please describe.**

I think reSolve is an incredible solution to reduce the time spent building infrastructure and increase the time spent with actual domain-related logic and I believe so many people could benefit from what this framework provides: more productivity. But **it's not clear what are the plans for the future of this project**.

- [Code frequency](https://github.com/reimagined/resolve/graphs/code-frequency) seems good, but there's no way to tell whether the commits are just fixing stuff or improving the framework.
- The same for [releases](https://github.com/reimagined/resolve/releases) which currently provide no information on what has been added/changed/fixed/removed.
- The [Twitter page](https://twitter.com/resolvejs) is so quiet. Just 96 followers at the time of writing. If reSolve wants to grow, it needs more engagement there.
- Searching for `resolvejs medium` or `resolvejs dev.to` brings so few results.

It's like this project is a hidden gem. It's probably not extremely popular because people don't know it exists. And those who get to know the project can't have any confidence in whether it will be thrown to oblivion six months from now.

**Describe the solution you'd like**

To start changing that scenario, I believe two things should be done:
- Create a roadmap so that people know what to expect for the future.
- Start filling the releases with changelogs of useful details and some emojis to be cool :smile: (see https://github.com/reimagined/resolve/issues/1373). 

**Describe alternatives you've considered**

None.

**Additional context**

How some projects are documenting their roadmaps:
- https://github.com/microsoft/TypeScript/wiki/Roadmap
- https://expo.canny.io
- https://trello.com/b/3klaHbfP/adonisjs-roadmap-2020
- https://github.com/flutter/flutter/wiki/Roadmap

How some projects are documenting their releases:
- https://github.com/Rocketseat/unform/releases
- https://github.com/mui-org/material-ui/releases
- https://github.com/dotansimha/graphql-code-generator/releases
- https://github.com/nestjs/nest/releases

**Comment by timbset** [comment]
@gustavopch , thank you for your suggestion. It is indeed a great idea to do this stuff. We need some time to discuss the matter within the team.
