### ISSUE TITLE
Use Husky and lint-staged to run tests on Git pre-commit and pre-push hooks

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1366]
**Is your feature request related to a problem? Please describe.**
Errors should be caught as early as possible.

**Describe the solution you'd like**
By using https://github.com/typicode/husky, it would be possible to:
- Automatically run `eslint` and `prettier` before committing;
- Automatically run all the tests before pushing.

Also, by using https://github.com/okonet/lint-staged it's possible to run those scripts faster because they will only run for files that were actually changed.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Lykoi18** [comment]
Hi Gustavo! Thanks for your suggestion. 

Our team uses the git-flow workflow, so test suites, linters, and so on, are invoked in response to pull requests, when a feature branch is ready to be merged into dev or a hotfix branch is ready to be merged into master. 

We often use feature branches for researches, spikes and similar stuff, so running tests preemptively is redundant for us. You can create a PR at any moment to force tests to tun, or you can run them manually on your local machine.

**Comment by gustavopch** [comment]
The redundancy there is useful. It's a matter of failing earlier and failing faster. If one needs to wait for manual intervention from someone else to know the PR is failing (or, to a lesser degree, even running a CI pipeline for every PR), the development cycle is just slower. The more the contributors can send ready-to-merge PRs, the more productive they will be. Ideally, people shouldn't need to revisit the same PRs multiple times. Ensuring code is tested before pushing just helps to achieve that.

In my own projects, I run some tests for every commit (like ESLint, Prettier, TypeScript type checking). By using lint-staged, I skip checks for most files that weren't affected by any changes. But those tests ensure that all my commits are in a good state.

I really believe Husky and lint-staged would add value for reSolve.

**Comment by Lykoi18** [comment]
Thanks, Gustavo. We will definitely discuss your proposal within the team.
