### ISSUE TITLE
Decide between singular or plural in `/api/query` Vs. `/api/commands`

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1367]
**Is your feature request related to a problem? Please describe.**
The endpoint to send commands is in the plural form: `/api/commands` (not `/api/command`). The endpoint for queries should follow the same convention.

**Describe the solution you'd like**
The `/api/query` endpoint should be changed to `/api/queries`. Next release could support both with a deprecation warning on `/api/query`.

**Describe alternatives you've considered**
There are a few alternatives:

1. Do the opposite and change `/api/commands` to `/api/command`. I personally dislike this one, but I understand it may be a matter of personal taste.

2. Let it be customized in the app config. This one would be the safest and more flexible choice. I like it.

**Additional context**
None.

**Comment by timbset** [comment]
Hi, @gustavopch  

Thank you for the suggestion, we highly appreciate it. We will look for the best way to make the framework’s API consistent. However, we need some time to do our research and make a right decision on this front.
