### ISSUE TITLE
Rename "projection" in the app config to "projections"

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1368]
**Is your feature request related to a problem? Please describe.**
For some reason, the property in the app config that defines the file implementing projections (for both aggregates, read models and view models) is named in the singular form. So you have:
```js
{
  name: 'ShoppingList',
  commands: 'common/aggregates/shopping-list.commands.js', // Plural
  projection: 'common/aggregates/shopping-list.projection.js' // Singular
}
```

**Describe the solution you'd like**
I believe that it should be named `projections` for the same reason that the property above is named `commands` in the plural form and not `command` in the singular form: the property points to a file that implements multiple projections, not a single one. This would be more consistent:
```js
{
  name: 'ShoppingList',
  commands: 'common/aggregates/shopping-list.commands.js', // Plural
  projections: 'common/aggregates/shopping-list.projections.js' // Plural
}
```

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by gustavopch** [comment]
Well, I'm not sure whether my reasoning above is correct.

The other interpretation would be that there are multiple projection handlers in the file, but they all work on a single projection (in other words, a single state/snapshot/entity/object). If this is the correct interpretation, then this issue can be closed.

**Comment by max-vasin** [comment]
> Well, I'm not sure whether my reasoning above is correct.
> 
> The other interpretation would be that there are multiple projection handlers in the file, but they all work on a single projection (in other words, a single state/snapshot/entity/object). If this is the correct interpretation, then this issue can be closed.

Hi! You are correct, this is exactly the intended interpretation. You can think of a "projection" as a set of event "transformations" that result in some arbitrary "state". And, because a projection file exports a single object containing such a set, the configuration option’s name is in singular form.

**Comment by gustavopch** [comment]
Thanks for the explanation, @max-vasin. That makes total sense.
