### ISSUE TITLE
Store more metadata within the events

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1369]
**Is your feature request related to a problem? Please describe.**
By looking at the events stored in the SQLite database, an event currently consists of the following properties:
- `threadId`
- `threadCounter`
- `timestamp`
- `aggregateId`
- `aggregateVersion`
- `type`
- `payload`

**Describe the solution you'd like**
I believe these properties should be added:
- `aggregateName`: so that `aggregateName` together with `aggregateId` may uniquely identify an aggregate instance.
- `contextName`: will be needed for the same purpose above in case https://github.com/reimagined/resolve/issues/1360 is implemented.
- `metadata`:
  - `causationId`: the ID of the command or event that originated this particular event.
  - `correlationId`: the ID of the command or event that originated this chain of events.
  - `initiator`: the object containing data that identifies the user or client that initiated this chain of events to improve the auditing capabilities.
    - `token`: the JWT token that was used.
    - `userId`: the user ID.
    - `ip`: the IP address of the client.
    - `ua`: the user agent string of the client.
    - `location`: the coordinates of the client according to the IP. This one is a little trickier as it would depend on a new adapter.
      - `latitude`
      - `longitude`

**Describe alternatives you've considered**
There's a similar issue that was closed saying that metadata should be stored within the payload (https://github.com/reimagined/resolve/issues/1214).

One of the main selling points of event sourcing is its auditability. It's hard to think of a situation where those properties wouldn't be desired. They are very helpful for auditing and debugging.

At the very least, `aggregateName`, `contextName` (in case https://github.com/reimagined/resolve/issues/1360 is implemented), `causationId` and `correlationId` should be stored automatically by the framework. In that case, there should be a way to let users implement a middleware to enrich the events with arbitrary data.

**Additional context**
- Explanation about correlation ID and causation ID: https://blog.arkency.com/correlation-id-and-causation-id-in-evented-systems
- Example of a provider that discovers a location based on a given IP address: https://ipstack.com
- Wolkenkit's command object structure: https://docs.wolkenkit.io/latest/reference/data-structures/commands
- Wolkenkit's event object structure: https://docs.wolkenkit.io/latest/reference/data-structures/events
- Commanded's commands documentation: https://github.com/commanded/commanded/blob/master/guides/Commands.md
- Commanded's events documentation: https://github.com/commanded/commanded/blob/master/guides/Events.md

**Comment by max-vasin** [comment]
Hi, @gustavopch ! Thanks for your proposal and links, they are indeed very useful!  Your event store middleware idea is also really interesting.

What comes to additional metadata, our framework is under heavy development and it is almost always very hard to tell exactly what metadata should be stored within events. Currently, we only add new metadata when a feature that is in development requires it. However, we will certainly put your suggestion on our backlog for future research.

**Comment by gustavopch** [comment]
@max-vasin  I believe the `aggregateName`, the `causationId` and the `correlationId` would be the most important to be handled natively by reSolve. The `contextName` may not be necessary as I explained in https://github.com/reimagined/resolve/issues/1360#issuecomment-618499925. The `token`, `userId`, `ip`, `ua` and `location` could all be handled in userland if reSolve had some sort of middleware. Unfortunately, I believe it currently can't be done in userland because command handlers don't have access to the HTTP request object.
