### ISSUE TITLE
Fix colors in the output of tests

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1370]
**Describe the bug**
When running the tests, "yarn" appears as red and "main" appears as yellow. It's really strange. Red is usually associated with errors and failures, yellow with warnings and green with success.

**To Reproduce**
1. Run `yarn test`.
2. See the output.

**Expected behavior**
Any other colors would not be as confusing as red and yellow. Even using plain white would be better.

**Screenshots**
![image](https://user-images.githubusercontent.com/10941958/79699102-9916c180-8263-11ea-96db-81caa04b6575.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.6.3-arch1-1
 - reSolve: 0.23.2

**Additional context**
None.

**Comment by sokolov11** [comment]
Hi Gustavo, thank you for your suggestion. The text output colors are determined by settings of the tool that we use to manage the monorepo and your terminal’s color settings. Currently, all color settings are set to their defaults. This configuration guarantees a good contrast between the terminal’s background and text under any environment. 
We will consider your suggestion to adjust colors used in some parts of the console output so they are closer to what the human perception expects.

**Comment by gustavopch** [comment]
@sokolov11 After submitting this issue I realized the colors are determined by `oao`. I didn't know that tool before. There must be some config to change the colors. It was really strange for me to run the tests and see a lot of red and yellow output. Of course, one can easily adapt to that, but it should be considered a matter of development experience for contributors outside the Reimagined team.
