### ISSUE TITLE
Tests failing due to timezone

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1371]
**Describe the bug**
When running the test script of [`resolve-scheduler-cloud`](https://github.com/reimagined/resolve/blob/master/packages/adapters/scheduler-adapters/resolve-scheduler-cloud/package.json) I got the following failure:
![image](https://user-images.githubusercontent.com/10941958/79699640-1d1e7880-8267-11ea-9070-e769a257d9c6.png)

That's because the timezone of my machine is `America/Sao_Paulo`. I could make that test succeed by running with `TZ=Europe/Moskow yarn test`.

**To reproduce**
1. Enter `packages/adapters/scheduler-adapters/resolve-scheduler-cloud`.
2. Run `TZ=America/Sao_Paulo yarn test` to simulate my timezone.
3. See the "start execution for an entry" test fail.

**Expected behavior**
I expected the test to work regardless of the timezone of my machine.

**Proposed solution**
Explicitly define `TZ=Europe/Moskow` in the `package.json`'s scripts that run the tests.

Maybe even start using `TZ=UTC` to be country-independent.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.23.2

**Comment by gustavopch** [comment]
The `resolve-module-admin` test also fails due to the timezone mismatch. Currently, I believe those are the only two affected packages (`resolve-scheduler-cloud` and `resolve-module-admin`), but of course, the solution must apply to tests from all packages in the monorepo.

**Comment by MrCheater** [comment]
Merged
