### ISSUE TITLE
Adopt conventional commits

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1373]
**Is your feature request related to a problem? Please describe.**
Currently, commits don't follow any particular pattern.

**Describe the solution you'd like**
I suggest that this project starts following the https://www.conventionalcommits.org pattern and that https://github.com/conventional-changelog/commitlint is configured for Husky (see https://github.com/reimagined/resolve/issues/1366) and within CI to enforce the usage.

Tools like https://semantic-release.gitbook.io can be integrated to automatically **bump the version**, **trigger releases** and **generate changelogs** according to the types of the last unreleased commits.

**Describe alternatives you've considered**
None.

**Additional context**
- Why use conventional commits: https://www.conventionalcommits.org/en/v1.0.0-beta.2/#why-use-conventional-commits
- How Semantic Release automatically determines the release type (major, minor, patch) by reading the commits: https://semantic-release.gitbook.io/semantic-release/#commit-message-format

**Comment by timbset** [comment]
@gustavopch  , thanks for the suggestion. We are going to discuss it within the team.
