### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1375]
**Is your feature request related to a problem? Please describe.**
Currently, it seems that the project doesn't have continuous integration. I could only find https://github.com/reimagined/resolve/blob/master/.drone.yml. I'm not familiar with Drone CI, so correct me if I'm wrong, but it appears it's only being used to handle publishing to NPM, not actually testing, checking code style, etc. for PRs.

**Describe the solution you'd like**
I believe it would be easier to guarantee that PRs follow the code style and don't introduce bugs if the project had GitHub Actions performing CI.

**Describe alternatives you've considered**
There are a lot of other CI tools, but GitHub Actions is pretty neat and easy to use :grin:.

**Additional context**
Maybe with a more automated test and release pipeline the project wouldn't even need the dev branch from Git flow and could just use [GitHub flow](https://guides.github.com/introduction/flow). In fact, it would be possible to use https://semantic-release.gitbook.io to automatically bump the version and publish to NPM right inside GitHub Actions after testing and everything else. Maybe that could enable a faster-yet-safe development cycle.

**Comment by IhostVlad** [comment]
Hi @gustavopch ! ReSolve framework does not use Drone for CI/CD (it's partially used for internal purposes), but uses GitLab CI/CD cloud server. There are two kinds of checks: merging feature branch into dev branch (small tests set - e.g. https://github.com/reimagined/resolve/pull/1338) and merging dev into master (also, new version publication - large tests set - e.g. https://github.com/reimagined/resolve/pull/1347)

So, resolve framework repository does already have tools for CI/CD automation and running unit and functional tests on PR's, including prettier, linter, test runner and so on.
Also take in mind, that resolve framework now is in deep development stage, and much breaking changes will still appear, so we prefer manual versioning with SEMVER compatibility

**Comment by gustavopch** [comment]
Thanks for clarifying @IhostVlad! Alright, now I realize there's a `ci/cd` branch. I'm not familiar with this approach of putting the CI on a separate branch. Did my PR (https://github.com/reimagined/resolve/pull/1374) trigger a pipeline on GitLab CI?

**Comment by MrCheater** [comment]
Unfortunately due to an accident last week, the our CI/CD server were de-energized.  I will fix it as soon as I can... 😔
