### ISSUE TITLE
Decide on a consistent file naming convention

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1377]
**Is your feature request related to a problem? Please describe.**
There are currently two naming conventions being used throughout the project:
- `kebab-case.js`
- `snake_case.js`

**Describe the solution you'd like**
I believe files should follow the same convention. I personally prefer `kebab-case.js`.

**Describe alternatives you've considered**
There are other conventions:
- `snake_case.js`
- `PascalCase.js` for classes/interfaces and `camelCase.js` for other files

I'd argue against the latter because:
- it's harder to read when the name is long (especially when there are lots of files in the same folder)
- it's harder to read when there are "I"'s and "l"'s which are different characters but seem equal

**Additional context**
None.

**Comment by MrCheater** [comment]
Kebab-case is, in my opinion, the most beautiful of identifier cases for file names. I want to convert file names into kebab-case. @IhostVlad , what do you think about this?
