### ISSUE TITLE
Use eslint-plugin-import to enforce alphabetic order within imports

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1378]
**Is your feature request related to a problem? Please describe.**
It's easier to find specific imports in files with lots of imports if they are always ordered similarly.

**Describe the solution you'd like**
I suggest that import order is enforced by ESLint like the following:
```
import { bar } from 'bar'
import { foo } from 'foo'
import { qux } from '../../qux'
import { baz } from '../baz'
```

**Describe alternatives you've considered**
There are some variants for import order, but I believe the most important thing here is:
- first imports from node_modules (in alphabetized order);
- then relative imports (in alphabetized order) with farthest above and nearest below.

**Additional context**
None.

**Comment by MrCheater** [comment]
@gustavopch , Thank you for your suggestion. I agree that we should begin using an https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#alphabetize-order-ascdescignore-caseinsensitive-truefalse
