### ISSUE TITLE
Place all devDependencies in the root-level package.json

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1380]
**Is your feature request related to a problem? Please describe.**
One of the main benefits of monorepos is the ability to have a unified workflow across all the packages. Sharing configuration files and using the same dependencies (at the same versions) throughout the monorepo move us closer to that unified workflow.

There's a reason why `dependencies` and `peerDependencies` can't be moved to the root-level `package.json`: the packages are independently published to NPM. So any single package published to NPM must have its own `dependencies` and `peerDependencies` listed, otherwise people installing that package would have trouble because their `node_modules` wouldn't include the required dependencies.

On the other hand, the reason above (as far as I can tell) doesn't apply to `devDependencies`. They are only useful to the developers of reSolve and won't be used by those consuming the packages published to NPM.

**Describe the solution you'd like**
I believe `devDependencies` should always be placed in the root-level `package.json`.

**Describe alternatives you've considered**
None.

**Additional context**
Side notes:
- There are things listed as `dependencies` which should actually be placed inside `devDependencies` (and thus also moved to the root-level `package.json`) like here: https://github.com/reimagined/resolve/blob/ac9644ba0de81b788a2f770957fcdb30d316dcb7/examples/hello-world-typescript/package.json
- It would be nice to have an automated way to check differently-versioned `dependencies` and `peerDependencies` across the packages to help to keep them synchronized. This tool seems to do the job: https://github.com/boneskull/sync-monorepo-packages. There's also https://github.com/renovatebot/renovate which would probably accomplish the same result by keeping all dependencies at the latest version.

**Comment by MrCheater** [comment]
Thanks for the suggestion. I will carefully study the possibility to place all devDependencies in the root-level package.json and get familiar with the tools you proposed. However, it can take some time before I research everything and be able to make any decision.

**Comment by gustavopch** [comment]
@MrCheater Sure thing. Let me know if I can help you with more information.
