### ISSUE TITLE
Verify usefulness of `resolve-es` tests

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1383]
I noted the tests in `resolve-es` seem to be testing code that's written in the test file itself, not in the source file.

For example in `loadEvents should perform events loading and transmitting from storage`:
- Lines 35-42 are testing the line 32.
- Lines 44 and 45 are testing the line 12.

The same happens with all other tests there: https://github.com/reimagined/resolve/blob/bfd909c31f6fd732caa505a434dbcca47f0338cc/packages/core/resolve-es/test/index.test.js

I have a suggestion for one test that would actually be testing something that's implemented in the source file:
```js
it('should propagate the event', async () => {
  const event = {
    aggregateId: 'ID',
    aggregateVersion: 1,
    type: 'EVENT',
    payload: {},
    timestamp: 1,
  }

  const storage = {
    loadEvents: jest.fn(),
    getNextCursor: jest.fn(),
    getLatestEvent: jest.fn(),
    saveEvent: jest.fn().mockReturnValue(Promise.resolve(event)),
    import: jest.fn(),
    export: jest.fn(),
    dispose: jest.fn(),
  }

  const publishEvent = jest.fn()

  const eventStore = createEventStore({
    storage,
    publishEvent,
  })

  await eventStore.saveEvent(event)

  // This would test the code that's implemented in packages/core/resolve-es/src/index.js#L11
  expect(publishEvent).toHaveBeenCalledWith(event)
})
```

**Comment by timbset** [comment]
Thanks for the suggestion. We will check out what we can improve here.

**Comment by gustavopch** [comment]
Now I realize what's actually being tested is whether calling `eventStore` methods cause the equivalent `storage` methods to be called. Perhaps changing the titles of the tests would make that clearer:
```diff
-  it('saveEvent should save and propagate event', async () => {
+  it('saveEvent is delegated by the event store to the storage adapter', async () => {
```
