### ISSUE TITLE
Fix modules option inside getBabelConfig helper

### ISSUE THREAD

**Issue by gustavopch** [reimagined/resolve#1386]
Passing `'false'` as a string to the `modules` option is unsupported by `@babel/preset-env` and will throw an error once `reSolve` updates its dependency to v7.9.5:
https://github.com/reimagined/resolve/blob/bfd909c31f6fd732caa505a434dbcca47f0338cc/packages/internal/helpers/get-babel-config.js#L27-L36

It should be passed as a boolean:
```diff
- modules = 'false'
+ modules = false
```

Release notes: https://github.com/babel/babel/releases/tag/v7.9.5

**Comment by MrCheater** [comment]
Hi @gustavopch . Thanks for the suggestion! Fixed https://github.com/reimagined/resolve/commit/5902ce82af1e464da613345a5fa5c5b23270277d
