### ISSUE TITLE
The grouping operation is not supported in resolvers

### ISSUE THREAD

**Issue by nikita-ashmarov-dx** [reimagined/resolve#1393]
There is no way to process data grouped by any column.

**Comment by superroma** [comment]
I'm reminding that in CQRS system you should do computations when updating read model, not when processing the query.
If i understand you correctly, you want to perform aggregation operation (GROUP BY in SQL) - then it is quite costly for the server resources. So I would put the aggregation operation into projection function.
Or, if all the data for grouping is already returned by query, do it on the client.

If you really need to perform complex SQL operations, you still can talk to the database directly and send any SQL query that it supported by underlying db engine.

**Comment by max-vasin** [comment]
@superroma gave correct point of view to this issue. We avoiding of adding complex query operations.
