### ISSUE TITLE
Can't install resolve example if you have old create-resolve-app in global node modules.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1412]
Can't install resolve example if you have old create-resolve-app in global node modules.
For example, I had an old version of the create-resolve-app:
npm -v create-resolve-app
6.12.0
and made attempt to install an example via npx as described in the documentation.
<img width="1717" alt="Screenshot 2020-06-18 12 16 06" src="https://user-images.githubusercontent.com/5825789/85006551-ee3b5a80-b162-11ea-8d92-d55b9ca5630e.png">

And I received the error.

Quick fix for this issue was to remove create-resolve-app package:
npm uninstall create-resolve-app

But we should handle this case without failing somehow. It could look broken for customers and developers who want to test and use resolve.

**Comment by superroma** [comment]
At very least provide an informative error message

**Comment by const314** [comment]
Starting from version 0.25.7, a warning and instruction about using the outdated global package is displayed. 
Application creation completes successfully with 0.25 or 0.26 global installation.
