### ISSUE TITLE
Event bus migration issues

### ISSUE THREAD

**Issue by arubtsov** [reimagined/resolve#1432]
**Describe the bug**
1) `npm run dev` results in the following error unless `dropEventBus` is specified:
```javascript
[Error]
Error while communication with reSolve HTTP server at port 3000
Maybe multiple instances of reSolve applications trying to run with similar port
HTTP response Error
```
2) `dorpEventBus` and `dropEventStore` options are not sufficient for migration. Removing of *.db files is also needed.
Errors before dbs deletion: [teamcity tack report](https://teamcity.devexpress.devx/viewLog.html?buildId=1146857&buildTypeId=TestCafe_Dashboard_FunctionalTests&tab=buildLog&_focus=637#_state=623,637)

**To Reproduce**
1. create-resolve-app -e hacker-news
2. modify run.ts under case 'dev' dropEventBus to false
3. yarn dev

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.24.2

**Comment by max-vasin** [comment]
Reproduced as:
* create-resolve-app -e hacker-news
* modify run.ts under case 'dev' dropEventBus to false
* yarn dev
