### ISSUE TITLE
Snapshot methods not exposed  on PostgreSQL eventstore adapter

### ISSUE THREAD

**Issue by adebisi-fa** [reimagined/resolve#1433]
**Describe the bug**
The already implemented snapshot methods (load, save, and drop) are not exposed on the [resolve-eventstore-postgresql](https://github.com/reimagined/resolve/tree/master/packages/adapters/eventstore-adapters/resolve-eventstore-postgresql) adapter.

**To Reproduce**
1. Use `resolve-eventstore-postgresql` adapter for eventstore.
2. Raise domain events e.g. via REST (/api/commands) using Postman or Insomnia.
3. First event is pushed to the store, but subsequent events throws error.

**Expected behavior**
Event should appears in the 'events' (or whatever the eventsTableName is set to) table.

**Screenshots**
Resolve throws a "pool.eventstoreAdapter.saveSnapshot is not a function" error.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux (Pop_!OS 20.04]
 - Browser [e.g. Firefox] (Not Applicable, though)
 - Version [e.g. 77.0.1]

**Additional context**
None.

**Comment by max-vasin** [comment]
Hi, adebisi-fa.
This is a bug, indeed. Thank you for reporting it to us and for sharing the fix. I must say though that our development workflow requires the use of the **dev** branch. For this reason, all PRs should be created with that branch. Would you please create a corresponding PR?

**Comment by adebisi-fa** [comment]
Dear @max-vasin ,

Noted, please.

I'll treat ASAP.

Thanks once again for the awesome work your team's doing with resolve!

Regards.


Foluso.

**Comment by adebisi-fa** [comment]
Thanks, please!
