### ISSUE TITLE
Command returns 500 instead of 409 in case of concurrency error

### ISSUE THREAD

**Issue by SergeyShurygin** [reimagined/resolve#1446]
Error in logs:
Jun 26 2020 14:00:12: 2020-06-26T14:00:12.534Z resolve:resolve-runtime:command-handler Command handler failed /api/commands/ Error: Can not save the event because aggregate 'af95f187-7ec4-4044-8e94-411357cdadd8' is not actual at the moment. Please retry later. Jun 26 2020 14:00:12: at invokeFunction (/var/task/node_modules/resolve-cloud-common/lambda/invokeFunction.ts:39:13)

**Comment by MrCheater** [comment]
Fixed in version 0.24.11
