### ISSUE TITLE
Events with dots in their type won't be passed to read models at realtime

### ISSUE THREAD

**Issue by const314** [reimagined/resolve#1459]
**Describe the bug**
Events with dots in their type won't get to the read model handlers when they appear but only on application restart.

**To Reproduce**
1. Create an event with type using dots: 'some.domain.event'
2. Create a read model that handles it, put console.log with event information in the handler.
3. Run the app and execute command that raises this event.
4. No output in the console
5. Restart the app, now event info appears in the console

**Expected behavior**
Event types with dots should be fully supported as it is a common scenario.

**Comment by IhostVlad** [comment]
Fixed on 0.24.12
