### ISSUE TITLE
Error in secret manager: "invalid input syntax for type uuid"

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1480]
**Describe the bug**
Looks like Secret Manager only supports uuid as aggregate ids. 
https://github.com/reimagined/resolve/blob/master/packages/adapters/eventstore-adapters/resolve-eventstore-postgresql-serverless/src/init.ts#L29

**To reproduce**
In our app, we are using shortId https://www.npmjs.com/package/shortid

**Comment by MrCheater** [comment]
Fixed in version 0.25.0
