### ISSUE TITLE
The eventstoreAdapter.rollbackIncrementalImport function raises an exception.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1504]
We use the following api handler in order to commit events import:

const handler = async (request, response) => {
	const requestData = JSON.parse(request.body);
	const importId = requestData.importId;

	const eventstoreAdapter = request.resolve.eventstoreAdapter;
	try {
		await eventstoreAdapter.commitIncrementalImport(importId);
	} catch (error) {
		await eventstoreAdapter.rollbackIncrementalImport();
		throw error;
	}
};

When the eventstoreAdapter.commitIncrementalImport call is failed by any reason, the eventstoreAdapter.rollbackIncrementalImport call raises the following exception:
"SQLITE_ERROR: no such table: events-incremental-import".

**Comment by MrCheater** [comment]
Fixed in version 0.25.4
