### ISSUE TITLE
create-resolve-app never ends, stuck on "Load example"

### ISSUE THREAD

**Issue by moshfeu** [reimagined/resolve#1510]
**Describe the bug**
When I try to create an app using the cli, the process never ends. The last line in the terminal is "Load example"

**To Reproduce**
1. Open terminal
2. Run `npx create-resolve-app my-awesome-app`

**Expected behavior**
The process creates `my-awesome-app` folder and finish.

**Screenshots**

![Screen Shot 2020-08-31 at 10 23 03](https://user-images.githubusercontent.com/3723951/91693621-fa389500-eb73-11ea-99f7-1e207b35d394.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - macOS 10.15.5 (19F101)
 - Browser [e.g. chrome, safari] - irrelevant
 - Version **0.25.0**

**Additional context**
Tried w/o `npx` and w/o `based on` - same results

**Comment by MrCheater** [comment]
Hi @moshfeu, Thanks for the suggestion!
Please specify the node.js version.
We have tested the create-resolve-app with the following versions:
v10.21.0
v12.18.3
v14.9.0
Everything is working fine.
We decided to add tracing (debug, debug levels) to better diagnose problems.

**Comment by moshfeu** [comment]
It's v12.13.1. But now it's working. Maybe it was in my end somehow..
