### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near ")": syntax error

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1512]
**Describe the bug**
After upgrading to the V0.25.1 we start receiving the following warning:
`UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near ")": syntax error`
Look like it just a warning and it does not break anything. 

**To Reproduce**
I can't reproduce it on the existing examples, we receive this warning only in the Brecomputer app after the first command execution.

**Comment by MrCheater** [comment]
Fixed in version 0.25.4
