### ISSUE TITLE
There is no documentation about view model authorization.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1514]
**Describe the bug**
In version 0.25.0 added view model authorization feature, here is a snippet from the 'personal-data' example:
https://github.com/reimagined/resolve/blob/master/examples/personal-data/common/view-models/current-user-profile.resolver.js
But there is no mention in docs about it.

**Comment by Lykoi18** [comment]
The description is in the read-side section: https://github.com/reimagined/resolve/blob/master/docs/read-side.md#view-model-resolver
