### ISSUE TITLE
Error: Subscribe adapter not initialized

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1521]
**Describe the bug**
Error in view-model subscribe adapter during navigation between pages connected to view-models https://github.com/reimagined/resolve/blob/master/packages/core/resolve-client/src/subscribe-adapter.ts#L87

**Comment by Matosov** [comment]
The same problem occurs in the Saturn application after the 0.25.3 version intergration.
It causes serious problems in the Saturn functionality.

**Comment by Lykoi18** [comment]
Fixed in version 0.25.5
