### ISSUE TITLE
create-resolve-app erases existing directory

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#1533]
**Describe the bug**
If i ran create-resolve-app with app name of existing directory, it completely erases its content.

**To Reproduce**
1. `mkdir app01`
2. `touch ./app01/myfile`
3. `npx create-resolve-app app01`
4. `ls ./app01/myfile` - No such file or directory

**Expected behavior**
create-resolve-app should throw an error if target directory is not empty.

I found that create-react-app does not look at hidden directories, so initialized empty git repo works.

**Desktop (please complete the following information):**
 - OS: osx catalina
 - Browser -
 - Node.js 10.15.3
 - ReSolve Version 0.25.4

**Comment by Lykoi18** [comment]
Fixed in version 0.25.7
