### ISSUE TITLE
Hacker news example import does not work.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1536]
**Describe the bug**
Hacker news example import does not work.

**To Reproduce**

1. npx create-resolve-app hacker-news-example -e hacker-news
2. cd hacker-news-example
3. npm run import
4. 
![image](https://user-images.githubusercontent.com/5825789/92602303-a423ca00-f2b6-11ea-9ca4-7ebabb4b9dc5.png)

**Expected behavior**
Data import should work. Or should be removed from the demo and replaced by some random data.

 - ReSolve Version [e.g. 0.25.5]

**Comment by Lykoi18** [comment]
Fixed in version 0.25.6
