### ISSUE TITLE
Cannot render stories when run HackerNews example

### ISSUE THREAD

**Issue by foreseaz** [reimagined/resolve#1543]
**Describe the bug**
After create an example with hacker news commands as
```
npx create-resolve-app hacker-news-example -e hacker-news
```
and then run with `npm run dev` or `npm run start`, the landing page is blank as following screenshot.

![image](https://user-images.githubusercontent.com/5697641/92907887-5050e680-f458-11ea-962f-ef2eb57970c8.png)

Found that the request of `first=NaN` not sure if this is the problem.
```
Request URL: http://localhost:3000/api/query/HackerNews/allStories?first=NaN&offset=21
```

Is there any other process that I am missing here? Thanks for the following up.

**Comment by Lykoi18** [comment]
Hi @foreseaz!
The `create-resolve-app` command creates an empty application without events.
You can update the resolve version to v0.25.6 and use `npm run import` to import events from news.ycombinator.com or create your own stories.
