### ISSUE TITLE
Enabling inline ledger option breaks status reporting for read models in CLI

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1554]
**Describe the bug**
Enabling inline ledger option breaks status reporting for read models in cli

**To Reproduce**
1. Enabling inline ledger option (btw it is not described in docs how to enable it)
2. Deploy app to the cloud
3.  yarn resolve-cloud read-models list
4. See that status is empty
![image](https://user-images.githubusercontent.com/5825789/93325206-9c68a600-f81f-11ea-963a-da0cb28422f0.png)

**Desktop (please complete the following information):**
 - ReSolve Version [e.g. 0.25.7]

**Comment by IhostVlad** [comment]
Fixed in 0.30.1
