### ISSUE TITLE
useReduxReadModel uses mutable data structures?

### ISSUE THREAD

**Issue by oliversturm** [reimagined/resolve#1576]
In [this example](https://github.com/oliversturm/resolve-tests/blob/redux/resolvedemo1/client/components/CustomerOverview.js) I use `useReduxReadModel` to load data - not using optimistic actions. The sample works correctly, but I see unexpected information in the Redux debugger. 

When the read model loads, the debugger displays two actions:

<img width="1758" alt="image" src="https://user-images.githubusercontent.com/4730969/94804341-91e30a80-03e2-11eb-8839-8b06dad778df.png">

<img width="1758" alt="image" src="https://user-images.githubusercontent.com/4730969/94804420-b2ab6000-03e2-11eb-863f-d5f504754db7.png">

You can see that the `data` is populated in the second action - it is not included in the first. 

However, if I check the state in the debugger for each action, I see this:

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/4730969/94804540-e38b9500-03e2-11eb-8951-bcfa91e488c8.png">

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/4730969/94804611-ff8f3680-03e2-11eb-998e-8a41b857f34a.png">

There is no difference! Obviously the state after the `...REQUEST` action should not include the data yet - but it does. Of course the `status` field should also not show "ready" at this point.

I suspect that mutable data structures are used internally, so that the state reflected by the debugger seems to be equal.

**Comment by max-vasin** [comment]
That's weird. I will look closer to it.
