### ISSUE TITLE
Clean up templates

### ISSUE THREAD

**Issue by oliversturm** [reimagined/resolve#1579]
I believe this is already work in progress, but I thought I'd mention it anyway. The current set of templates outlines various different approaches, which is cool for demos - but these are templates, not demos. I think we should carefully structure a set of templates to get started with, based on certain preferences, and not try to demonstrate different complicated implementations in them.

A second point to "clean up" is the code in general. There are outdated elements, code left behind from previous iterations, and stuff like this:

```js
const { name } = command.payload
validate.fieldRequired(command.payload, 'name')
```

**Comment by oliversturm** [comment]
Forgot this point that is separate in my notes: use current package versions! I found a react-bootstrap version in one template that is truly ancient...

**Comment by max-vasin** [comment]
Yes, you're right, there is some mess. About react-bootstrap - only last shopping-list-with-redux-hooks example received updated version. It can be tricky to update existing examples because of many breaking changes, but it, surely, must be done.

**Comment by const314** [comment]
Starting from version 0.31.0, we separated templates that implement basic functionality from examples that cover more advanced scenarios. Package versions were updated to most recent as well.
If necessary, it is still possible to use these advanced examples as templates on app creation.
