### ISSUE TITLE
ECONNREFUSED at the end of npx run

### ISSUE THREAD

**Issue by oliversturm** [reimagined/resolve#1585]
```
➜ npx create-resolve-app myapp

...

Happy coding!
Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

That error message at the end appears every time for me, on two different systems. Using Node 12.18.3 (or .4 on the other machine), npm 6.14.6.

**Comment by const314** [comment]
Cannot reproduce it on the latest version.
Feel free to reopen if the issue is still reproduced on your side.
