### ISSUE TITLE
An error occurs when the u9jdwtdb7tj5nd64iytrs8uhhkv3 application read model is being built.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1593]
yarn resolve-cloud read-models list u9jdwtdb7tj5nd64iytrs8uhhkv3
yarn run v1.22.5
.../node_modules/.bin/resolve-cloud read-models list u9jdwtdb7tj5nd64iytrs8uhhkv3
NAME                           STATUS                         LAST EVENT                         LAST ERROR                                                                                          
Saturn                         error                          1/2/01 00:00:00 Company_Registered TypeError: Cannot read property 'join' of undefined     at loadEventsByCursor                       
                                                                                                 (/var/task/node_modules/resolve-eventstore-postgresql-serverless/src/js/load-events-by-cursor.js:16…
                                                                                                 0:25)     at process._tickCallback (internal/process/next_tick.js:68:7)                             
✨  Done in 11.87s.

**Comment by Matosov** [comment]
The same events are correctly built into the read model locally.

**Comment by max-vasin** [comment]
@Matosov is it still actual?

**Comment by Matosov** [comment]
@max-vasin 
Fixed in 0.25.12.
