### ISSUE TITLE
useCommandBuilder only works with single-parameter functions

### ISSUE THREAD

**Issue by oliversturm** [reimagined/resolve#1595]
The [documentation here](https://github.com/reimagined/resolve/blob/master/docs/api-reference.md#usecommandbuilder) claims that `useCommandBuilder` helps generate commands "based on input parameters" (plural!). However, in my tests it seems that only delegates with one parameter are handled correctly.

This does not work - `name` and `image` are `undefined`, while the `id` has a value.

```js
  const updateProduct = useCommandBuilder((id, name, image) => ({
      aggregateName: 'product',
      aggregateId: id,
      type: 'updateProduct',
      payload: { name, image },
    }), []);
```

**Comment by max-vasin** [comment]
You can always "pack" parameters to single object:
```js
  const updateProduct = useCommandBuilder(({ id, name, image }) => ({
      aggregateName: 'product',
      aggregateId: id,
      type: 'updateProduct',
      payload: { name, image },
    }), []);

```
We have been try to make builder function with more than one argument, but current (on the time of implementation) version of typescript was unable to infer argument types for it, only for first one. Maybe current typescript allow this. I'll mark this issue as improvement.

**Comment by oliversturm** [comment]
Okay, that's fine with me (and what I did in my project). In this case I guess the docs should be improved to explain the expected behavior better.

**Comment by max-vasin** [comment]
Since 0.25.14 command builder have variadic generic argument list with valid type inferring.
