### ISSUE TITLE
Subsequent calls on SecretsManager.setSecret doesn't replace exisiting records

### ISSUE THREAD

**Issue by SergeyShurygin** [reimagined/resolve#1603]
**To Reproduce**

//somethere in api handler:

secretsManager.setSecret('token', 'token1');
const  token1 = await secretsManager.getSecret('token');//this return 'token1'
secretsManager.setSecret('token', 'token2');
const  token2 = await secretsManager.getSecret('token');//this should return 'token2', but still returns 'token1'

**Expected behavior**

second call of secretManaqer.setSecret should replace 'token1' with 'token2'

**Comment by max-vasin** [comment]
This will be forbidden in next version. Secret cannot be reassigned for the same id.
