### ISSUE TITLE
It is not clear from the docs where view model resolver should be added.

### ISSUE THREAD

**Issue by arubtsov** [reimagined/resolve#1604]
I would add an example of a view model [configuration](https://github.com/reimagined/resolve/blob/b1771c715e041af97529ab210798ca25e9bacbd1/examples/personal-data/config.app.js#L24) to [this](https://github.com/reimagined/resolve/blob/master/docs/read-side.md#view-model-resolver) doc.

**Comment by EugeniyBurmistrov** [comment]
We have added the missing content to the [View Model Resolver](https://github.com/reimagined/resolve/blob/dev/docs/read-side.md) section.
