### ISSUE TITLE
useReduxViewModelSelector returns undefined if 'selectorId' is passed as parameter

### ISSUE THREAD

**Issue by sky3d** [reimagined/resolve#1605]
**To Reproduce**
Define view model with named selector:
`
// ...
  const { connect, dispose, selector } = useReduxViewModel(query, {
    selectorId: 'selector-key',
  })
`

Try to obtain data
`
//...
const { data } = useReduxViewModelSelector('selector-key')
`

**Comment by max-vasin** [comment]
Update: same issue in useReduxReadModelSelector. Caused by absence of initial state value in both hooks. #1606 fixes another reason of same issue.
