### ISSUE TITLE
Please add a possibility to use like-operators in the store.find expression.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1609]
Very often the Saturn users search for records that contain some text, for instance all Companies with the 'OOO' text within the Name field.

For example, the searching expression looks as follows on the Transact-SQL:
select * from Companies where Name like '%OOO%'

The same functionality could look the following way in resolve:
store.find(
    'Companies',
    { $like: { name: '%OOO%'}}
);
or something else at your preference.

**Comment by max-vasin** [comment]
We suggest to build a read model based on special search engine, such as Elastic Search. It will be much more efficient and productive.
