### ISSUE TITLE
loadEventsByTimestamp in resolve-eventstore-postgresql and resolve-eventstore-postgresql-serverless check timestamps against wrong column name

### ISSUE THREAD

**Issue by jodysimpson** [reimagined/resolve#1651]
**Describe the bug**
The function `loadEventsByTimestamp` within modules `resolve-evenstore-postgresql` and `resolve-eventstore-postgresql-serverless` both error out when using a `startTime` or `finishTime` argument.  This is due to the query being built checking against the column name `startTime` and `finishTime` instead of `timestamp`.

**To Reproduce**
call `loadEventsByTimestamp` with a `startTime` or `endTime` property in the 2nd object argument.

**Expected behavior**
The function returns a query error from PostgreSQL at the moment.  It should return the results of the executed query.

**Comment by MrCheater** [comment]
Fixed in version 0.26.5
