### ISSUE TITLE
It is impossible to build and start resolve applications in the Windows-8.1 with NodeJS-14.15.1.

### ISSUE THREAD

**Issue by Matosov** [reimagined/resolve#1652]
Try to execute the yarn command for the shopping-list-with-redux-hooks sample.
The following log is received as a result:
[1.txt](https://github.com/reimagined/resolve/files/5689672/1.txt)

It worked correctly with previous NodeJS versions (12.20.0 for instance).

**Comment by max-vasin** [comment]
Currently, there is no Node 14.x support, but we have plans to upgrade in one of future versions.
