### ISSUE TITLE
Upload validator bapass

### ISSUE THREAD

**Issue by lokeex** [reimagined/resolve#1658]
**Describe the bug**
The full upload step:
1. Get jwt token from server
2. Get upload url from server
3. Send upload request

We can skip the first and second step to send upload request directly.

**To Reproduce**
1. Run https://github.com/reimagined/resolve/tree/master/examples/cli-uploader
2. Send put requests 
`curl -X PUT -d '111' "http://localhost:3000/uploader?dir=../../../../../../../../../../tmp&uploadId=111"`

**Expected behavior**
403 or other forbidden description

**Screenshots**
![image](https://user-images.githubusercontent.com/73454408/102959264-f44b3300-4519-11eb-9f83-cdc0927b90ea.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Node.js Version 12.19.0
 - ReSolve Version 0.26.3

**Additional context**
There are no validator in resolve-runtime/lib/common/handlers/uploader-handler.js,
and the req.query.dir is directly passed to path.join, it will cause path traversal by using ".."

**Comment by max-vasin** [comment]
Hi, @lokeex. Thanks for reporting a bug!

**Comment by Lykoi18** [comment]
Fixed in 0.26.4 version
