### ISSUE TITLE
Duplicate identifier 'LibraryManagedAttributes'

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#1713]
**Describe the bug**
Newly created resolve TypeScript app cannot run with error: Duplicate identifier 'LibraryManagedAttributes'

**To Reproduce**
1. `npx create-resolve-app myapp -e hello-world-typescript`
2. `cd myapp`
3. `yarn`
4. `yarn dev`
5. see lot of ts errors

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.2
 - Safari
 - Node.js Version 10.15.3
 - ReSolve Version 0.26.5

**Comment by superroma** [comment]
The workaround is to add a resolution section to package.json as [described on SO](https://stackoverflow.com/questions/52399839/duplicate-identifier-librarymanagedattributes)
```
  "resolutions": {
    "@types/react":"^16.8.8"
  }
```

**Comment by const314** [comment]
Fixed in 0.31.0
