### ISSUE TITLE
"Error: Command handler is disposed" in API-Handler that uses executeCommand in an async manner

### ISSUE THREAD

**Issue by snizzl** [reimagined/resolve#1716]
**Describe the bug**
Newly created resolve app throws "Error: Command handler is disposed" when using resolve.executeCommand inside an API-Handler that delays the execution.

**To Reproduce**

1. `npx create-resolve-app my-awesome-app`
2. `cd my-awesome-app`
3. Create a simple aggregate inside the given file `aggregate-name.commands.js` e.g.
```
export default {
    dummy: () => {
        console.log('EXECUTE COMMAND');
    }
};
```
4. Inside `config.app.js` add an API-Handler to `appConfig` e.g. 
```
  apiHandlers: [
      {
          path: '/api/handle',
          handler: 'common/api-handlers/handler.js',
          method: 'GET',
      }
  ],
```
4. Create the file `common/api-handlers/handler.js` (and the folder structure)
5. Add the function to the newly created file e.g.
```
export default ({resolve}, res) => {
    setTimeout(() => resolve.executeCommand({
        aggregateName: 'aggregate-name',
        aggregateId: '1234',
        type: 'dummy',
        payload: {}
    }), 0);
};
```
5. `npm run dev`
6. HTTP-Request to `http://localhost:3000/api/handle`
7. reSolve will throw:
```
resolve:resolve-command:getAggregateState:aggregate-name:1234 Command handler is disposed +0ms
resolve:resolve-command:getAggregateState:aggregate-name:1234 Command handler is disposed +0ms
(node:27571) UnhandledPromiseRejectionWarning: Error: Command handler is disposed
    at generateCommandError (/my-awesome-app/node_modules/resolve-command/src/index.ts:81:17)
    at /my-awesome-app/node_modules/resolve-command/src/index.ts:351:17
    at getAggregateState (/my-awesome-app/node_modules/resolve-command/src/index.ts:345:11)
```

**Expected behavior**
The command should be executed

**Desktop:**
    OS: Ubuntu 20.04
    Browser: Firefox 85.0.1
    Node.js: Version v15.9.0
    ReSolve: Version 0.26.5

**Comment by max-vasin** [comment]
Hi, @snizzl. The *resolve* context object contains resources, such as database connections, that are created before an API handler is invoked. These resources should be disposed after the API handler completes to prevent leaks, especially in the cloud environment. So the approach you described is not currently supported. Could you please elaborate what are you trying to achieve with this approach?

**Comment by snizzl** [comment]
Hey @max-vasin, 
thank you for your answer.
I checked again and the problem is indeed not a big deal. It occurs whenever the response is handled after the handler returns.
Like this:
```
const asyncStuff = async (resolve, res) => {
    await resolve.executeCommand({
        aggregateName: 'aggregate-name',
        aggregateId: '1234',
        type: 'dummy',
        payload: {}
    });
    res.end();
};

export default ({resolve}, res) => {
    asyncStuff(resolve, res);
};
```

For Express this is fine, but resolve seems to close some connections (as you said) after the handler returns.
But of course one would use something like:
```
export default async ({resolve}, res) => {
    await asyncStuff(resolve, res);
};
```
and everything works fine...

Maybe it's enough to update the docs to make this a bit more clear?

**Comment by EugeniyBurmistrov** [comment]
Hello @snizzl,
Thank you for the suggestion, we will update our docs to clearly state this limitation.
