### ISSUE TITLE
Current Status of Project and Future Plans?

### ISSUE THREAD

**Issue by AshleyAitken** [reimagined/resolve#1719]
Hi,

Thanks for sharing ResolveJS.

However, it's unclear from web site and GitHub repository what is the actual current status of the project, e.g. limitations, and future plans. 

It would be great to have a page with description of current limitations and future plans, possibly with an estimated timeline, for ResolveJS.

I have ascertained some limitations by reading through issues, documentation, and StackOverflow questions but this is not optimal or transparent.  

This would give me more confidence in committing a project to use ResolveJS. 

Thanks,
Ashley.

PS Apologies if I missed these somewhere...

**Comment by superroma** [comment]
Hi Ashley,

You are right there is no roadmap or limitation list at the moment. 

I guess there are lot of things reSolve cannot do out of the box, but as an opensource product anybody can contribute and add things that are missing.

Right now our team is focused on making platform for several internal projects, but we can add specific improvements based on your requirements. 

For our internal projects the main focus at the moment is developer experience. There are no known runtime issues. Meaning deployed application works fine. There are issues with importing large amounts of events, migrating between versions, performance of read models rebuilding. This is what we are focused on at the moment.

Againg, this is specifice for use cases we have on hand. Our primary use case is deployment to the serverless AWS cloud infrastructure. "Local" node.js app is used primarily for development and testing. 

Can you describe your use case? Do you have specific deployment ideas? Database system? Integrations?

**Comment by AshleyAitken** [comment]
Roman, thank you so much for you post.  May I suggest just having these sort of points on a page somewhere in the project would be super helpful as is your post.

I read somewhere that reSolve Cloud is not yet publicly released.  Is this true? I did setup an AWS account and visited resolve admin but didn't try to deploy sample app. 

My use case is an unfunded startup so I also appreciate developer experience but I am also concerned about platform longevity and/or ability to migrate if needed.  

To keep expenditure low I would like to deploy locally until if/when demand increases, then having reSolve Cloud would be great.  Cheers, Ashley.

**Comment by superroma** [comment]
Ashley, 

We have several apps running on reSolve "local" (as nodejs app) for couple of years, so we quite sure it works. 

Also, we obviously, very interested to have external users, so we are working closely with several teams to make sure their requirements are satisfied.

So, I promise our full support in fixing problems and developing features you may need.

Regarding cloud, it does not require you to have your own AWS account, and it is serverless - meaning it won't consume any resources when app is not used. So, it might be a good deployment option for your project. Contact us if you want to preview it.

Thanks
Roman

**Comment by superroma** [comment]
Forgot to mention,

The new release of reSolve is coming next week. There will be significant changes, package renames, do I suggest you not to start real project right now.

**Comment by AshleyAitken** [comment]
Thanks for the further information.

That all sounds very exciting and I am keen to try it out.

**Comment by AshleyAitken** [comment]
_[contact address removed by maintainer]_ is bouncing when send from different email addresses...

The response from the remote server was:
550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM6NAM11FT046.eop-nam11.prod.protection.outlook.com]

**Comment by superroma** [comment]
Oh, sorry, that was the wrong address.
