### ISSUE TITLE
[resolve-query] Add GraphQL Variables

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#173]
Use case:
/api/query/comments?query=query comment {CommentById(id: $id)}**&variables={id:"3d013c8b-10de-410e-a98f-3c48bb3be107"}**

**Comment by IhostVlad** [comment]
Implemented as:
`/api/query/comments?graphql=query {CommentById(id: $id)}&variables={id:"3d013c8b-10de-410e-a98f-3c48bb3be107"}`
