### ISSUE TITLE
 with-angular example does not work

### ISSUE THREAD

**Issue by emanuelcovaci** [reimagined/resolve#1795]
**Describe the bug**
 with-angular example does not work
**To Reproduce**

```
create-resolve-app resolve-example -e with-angular
cd ./resolve-example
yarn dev
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11509775/113846775-801e5d80-979f-11eb-90d5-89e39c5364c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Node.js Version 12.16.2
 - ReSolve Version  0.29.0

**Additional context**
Also I tried to create the example with npx & npm run dev
```npx create-resolve-app resolve-with-angular -e with-angular
cd resolve-with-angular 
npm run dev
```
But the same error occurred

**Comment by max-vasin** [comment]
Thank you for reporting the issue! We found a bug in our CI pipeline, that allowed this to happen. We'll fix it in the next version. As a workaround, add a *@resolve-js/client* dependency with `yarn add @resolve-js/client`.
