### ISSUE TITLE
Environment variable is not updated after subsequent deploys

### ISSUE THREAD

**Issue by AlexanderMoiseev** [reimagined/resolve#1833]
Environment var is not updated after subsequent deploys

  First way to reproduce
1) deploy an app with 'yarn resolve-cloud deploy -n app-1 --env VAR=env_v1' - ( env set correctly for the first time )
2) deploy an app again with the same name and different env value  'yarn resolve-cloud deploy -n app-1 --env VAR=env_v2' 
3) run yarn resolve-cloud environment list 
Result - env is not updated

  Second way to  reproduce
1) deploy an app with 'yarn resolve-cloud deploy -n app-1' ( don't provide env)
2) set env variable within existing deployment with ' yarn resolve-cloud environment set 'deployId' VAR=env_v1
2) remove this env from deployment with 'remove' command
3) deploy an app with with the same name and provide an env variable 'yarn resolve-cloud deploy -n app-1 --env VAR=env_v2' 
Result - env is not updated

Expected behavior
 env is updated after these steps

 - Node.js Version [e.g. 12.18.1]
 - ReSolve Version [e.g. 0.28.2]

**Comment by Lykoi18** [comment]
Fixed in 0.30.1
