### ISSUE TITLE
Testing tools: unable to set secrets manager

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#1844]
**Describe the bug**
Unable to set secrets manager in a read-model test using testing tools

**To Reproduce**
``` 
await givenEvents(events)
       .readModel({
          name: 'MyReadModel',
          projection,
          resolvers,
          encryption,
          adapter
       })
      .withSecretsManager(secretsManager)
```
returns error:
``` TypeError: (0 , _testingTools.default)(...).readModel(...).withSecretsManager is not a function ```

 - ReSolve Version 0.30.0

**Comment by max-vasin** [comment]
Version 0.30.0 introduces more strict way for writing BDD tests with compile & runtime checks. You can provide secrets manager to BDD test chain using **.withSecretsManager** selector just after **.query** selector.
E.g.:
```js
await givenEvents(events)
       .readModel({
          name: 'MyReadModel',
          projection,
          resolvers,
          encryption,
          adapter
       })
      .query('my-resolver', {})
      .withSecretsManager(secretsManager)
```
