### ISSUE TITLE
Read-model operations error : errno: 19,   code: 'SQLITE_CONSTRAINT'

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1856]
**Describe the bug**
After update to 0.30.1 resolve version, I received the following errors on the application local start with yarn dev:
````
Read-model operations error: subscribe BeerStyles [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: default__LEDGER__.Properties] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}

      Event subscriber "BeerStyles" can't resume subscription due to error "Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: default__LEDGER__.Properties"
````

**Comment by IhostVlad** [comment]
Resolve version `0.30.x` have some breaking changes in internal read-model ledger structure compare to `0.29.x` version. Please delete SQLite read-model files physically, aka remove all read-model dependent files in `data` folder.
