### ISSUE TITLE
It is not clear how to use aggregateId in aggregate tests.

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#1864]
It is not clear how to use "aggregateId" field in the aggregate tests. It is possible to set it givenEvents, but if it is different from default 'test-aggregate-id' it will be ignored by aggregate projection.

Maybe we should send a warning that aggregateId will be ignored if it is set and ignore it. Or document it in any other way. 
````
describe('aggregates', () => {
  test.only('ShoppingList Create', async () => {
    const event = await givenEvents([{
      type: SHOPPING_LIST_CREATED,
      payload: { name: 'TESTS' },
      aggregateId: 'test-aggregate-id1',
      timestamp: 1
    }])
      .aggregate(shoppingListAggregate, 'test-aggregate-id1')
      .command('createShoppingList', {
        name: 'Lager',
      })

    console.log(event)

  })
})
````

**Comment by const314** [comment]
Cannot reproduce on current version. Custom aggregateId works as expected in tests.
