### ISSUE TITLE
Small bug in code example for Step-by-Step Tutorial

### ISSUE THREAD

**Issue by pcopley** [reimagined/resolve#1869]
**Describe the bug**
Under [Sending Commands to an Aggregate](https://reimagined.github.io/resolve/docs/tutorial#sending-commands-to-an-aggregate), the first code sample's `payload` has a property called `text` when in all other instances that property is called `name`.

**To Reproduce**
1. Go to https://reimagined.github.io/resolve/docs/tutorial#sending-commands-to-an-aggregate

**Expected behavior**
Code sample should be:
```
{
  "aggregateName": "ShoppingList",
  "type": "createShoppingList",
  "aggregateId": "shopping-list-1",
  "payload": {
    "name": "Item 1"
  }
}
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
I am happy to submit a PR to fix this I just won't be able to get to it until next week and wanted to submit this while I was thinking of it.

**Comment by EugeniyBurmistrov** [comment]
Hi @pcopley,
Thank you for pointing out the issue. I fixed the code sample as a part of [this](https://github.com/reimagined/resolve/pull/1870) pull request. The fix will go public with the upcoming release.
