### ISSUE TITLE
The loadEvents function does not work if 'startTime' and 'endTime' parameters are specified

### ISSUE THREAD

**Issue by pavsenin** [reimagined/resolve#1903]
**Describe the bug**
The [loadEvents](https://reimagined.github.io/resolve/docs/api-reference#loadevents) API function does not work if _startTime_ and _endTime_ parameters are specified

**To Reproduce**
1. Execute the `https://d6i6g4.resolve.sh/api/loadEvents` request with the following event filter:
```
{
    startTime: new Date('2021-06-16T09:00:00').getTime(),
    endTime: new Date('2021-06-16T09:30:00').getTime(),
    limit: 2000,
    eventsSizeLimit: Number.MAX_SAFE_INTEGER,
    eventTypes: [
        REPORT_TASK_STARTED,
        REPORT_TEST_STARTED,
        REPORT_TEST_DONE,
        REPORT_TASK_DONE,
        UPLOAD_CREATED
    ]
}
```
2. See error
Error: ERROR: syntax error at or near ""sizedEvents""
  Position: 854

**Expected behavior**
All events between startTime and endTime are returned. 

**Desktop (please complete the following information):**
 - 0.30.5 ReSolve Version

**Comment by FreeSlave** [comment]
Fixed in https://github.com/reimagined/resolve/commit/8441c098e7caebe6486efb0deb73620ad6731b9e

**Comment by pavsenin** [comment]
Exactly the same request,

https://ddev.testcafe.io/api/loadEvents

The result:

Error: Invalid value undefined supplied to : EventFilterSchema/0: ({ limit: Int } & Partial<{ eventTypes: (Array<string> | null), aggregateIds: (Array<string> | null), eventsSizeLimit: Int }>)/0: { limit: Int }
