### ISSUE TITLE
Events imported with `incrementalImport` do not trigger read model update

### ISSUE THREAD

**Issue by maggo** [reimagined/resolve#1931]
I have a special case where I want to periodically import events with past timestamps into my event store. (Synchronizing blockchain events with a central database)

I tried calling `executeCommand` for each event, but it just sets the current timestamp, `scheduleCommand` doesn't do anything for past timestamps, so the events are dropped.

So I switched to `eventStore.incrementalImport` to import batches of events, and also ensure that no events are imported twice by accident, but it seems like the read model update is not triggered by this functionality. When I call `read-models resume` manually via module-admin I get the latest state.

Is there another way to do this, or a function to force the read model to be updated after my import?

**Comment by const314** [comment]
Hello,

I apologize for the delayed response.

You can resume the read model updates in your code by calling the following function:
`resolve.eventSubscriber.resume({ eventSubscriber: 'YourReadModelName' })`

If you have any further difficulties, don't hesitate to contact us at any time.

**Comment by superroma** [comment]
Sorry, clicked accidentally

**Comment by maggo** [comment]
Thanks for the info! I checked the module-admin source and also found this line in the resume API handler.

Consider this case closed, and thank you for your work on this project! :)
