### ISSUE TITLE
RESOLVE_DEPLOYMENT_DOMAIN is incorrect after using the `domains assign` command

### ISSUE THREAD

**Issue by aleks-pro** [reimagined/resolve#1933]
Steps to reproduce:
1. You should have a deployment with a domain assigned to it
2. Use the `domains assign` command to assign this domain to another deployment
3. Check RESOLVE_DEPLOYMENT_DOMAIN environment variable value in the first deployment. It is still linked to the domain

ReSolve Version 0.31.0

**Comment by MrCheater** [comment]
Environment variable "RESOLVE_DEPLOYMENT_DOMAIN" has been removed for multi-domain support reasons.
Workaround:
```sh
resolve-cloud env set <deployment-id> DEPLOYMENT_DOMAIN=your.domain.example.com
```
or 
```sh
resolve-cloud deploy --envs=DEPLOYMENT_DOMAIN=your.domain.example.com
```
