### ISSUE TITLE
CORS Headers for query endpoints

### ISSUE THREAD

**Issue by maggo** [reimagined/resolve#1937]
I'm currently using Resolve only for the server side and my client is running as a static website on another domain. The `/api/query/*` routes on the servers are public and meant to be accessed from the client.

When calling the endpoint URL directly everything works fine, but as soon as I try fetching the endpoints from my app the calls fail because of missing CORS Headers.

Is there a way to enable CORS for all routes? Or should I copy over the code from [query-handler.js](https://github.com/reimagined/resolve/blob/6355e807d6d8ef72517bffd9a13c6f8fbad5d079/packages/runtime/runtime/src/common/handlers/query-handler.js) into a new API handler?

**Comment by const314** [comment]
Starting from version 0.31.2, you can use a read model resolver middleware to implement such a scenario.
Here is an example:
```
const corsMiddleware = (next) => (
  middlewareContext,
  store,
  params,
  context
) => {
  const { res } = middlewareContext
  res?.setHeader('Access-Control-Allow-Origin', '*') //set any response headers here
  return next(middlewareContext, store, params, context)
}

export default corsMiddleware
```

You also need to add the middlewares section to your config.app.js file:

```
  middlewares: {
    readModel: { 
        resolver: ['common/middlewares/cors-resolver-middleware.js']  //path to your middleware file
    },
  },
```
We'll describe middlewares in our documentation in the nearest time.

**Comment by maggo** [comment]
Just tried it and confirmed working. Thank you!
