### ISSUE TITLE
The Replicator read model takes a lot of resources during replication of big event store (5kk events)

### ISSUE THREAD

**Issue by pavsenin** [reimagined/resolve#1949]
**Describe the bug**
The Replicator read model takes a lot of resources during replication of big event store (5kk events)

**To Reproduce**
Deploy replicator readmodel for big event store.

There are a lot of errors:
x0f8ha canceling statement due to statement timeout error	1,141
x0f8ha Query read timeout Error	611

99.9% "AWS/RDS", "CPUUtilization"

- ReSolve Version 0.31.3

**Comment by MrCheater** [comment]
500.000 event -  51 minutes
PASS  ./replication.test.ts (1143.975 s)
  Replication
    ✓ should deploy replica application (210757 ms)
    ✓ should deploy origin application (1143975 ms)
    ✓ should replicate all events and secrets from origin to replica (3061882 ms)

 5.000.000 event ~ 8 hours and 30 minutes
 I am waiting for the completion of the task "Resolve Gate"
