### ISSUE TITLE
Redeploy existing application automatically resume manually paused read model

### ISSUE THREAD

**Issue by pavsenin** [reimagined/resolve#1951]
**To Reproduce**

1. yarn resolve-cloud read-models pause deployId readmodel
2. Check that  readmodel is in skip mode
3. yarn resolve-cloud deploy -n existing-app
4. Check that  readmodel is in deliver mode

**Expected behavior**
Readmodel should be in skip mode until explicitly resume\reset

- ReSolve Version [e.g. 0.31.3]

**Comment by FreeSlave** [comment]
Same happens on manual reset. Probably the reset operation should not unpause the readmodel.

**Comment by MrCheater** [comment]
Fixed in version 0.31.6
