### ISSUE TITLE
Examples type safety not great in Typescript

### ISSUE THREAD

**Issue by mikecann** [reimagined/resolve#1965]
Hey guys, really appreciate you putting the time into making some typescript examples, sorry it has taken me so long to exploring them.

Although there are now some types it seems like there is an awful lot of "any" spread around the codebase. 

For [example](https://github.com/reimagined/resolve/blob/dev/examples/ts/hacker-news/common/aggregates/user.commands.ts#L9) none of the payloads are typed so everything is "any". Same goes for the aggregate state. 

If we set `"noImplicitAny": true` and `"strictNullChecks": true` (which should be the minimum for any modern TS project, ideally you should be using `"strict": true`) in the tsconfig.json we get all kind of errors. 

Currently as it stands there is little benefit to the TS examples over the JS ones.

**Comment by const314** [comment]
We are working on making reSolve fully typed. We still have some packages to convert to typescirpt first, so typing demos will take some time.
As for the case you mentioned, using 'any' for payloads type may be reasonable, at least if they are not used anywhere outside of the aggregate's commands and projections.
Let's convert this issue to a discussion and discuss the scenarios where types are mandatory in demos.
