### ISSUE TITLE
@resolve-js/core package goes to client

### ISSUE THREAD

**Issue by aleks-pro** [reimagined/resolve#1973]
**Describe the bug**
Script from @resolve-js/core package goes to client

**To Reproduce**
Create resolve app that uses @resolve-js/client package 

- ReSolve Version 0.31.4

**Comment by MrCheater** [comment]
**Additional Context:**
Client-side entry point: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser
Server-side entry point: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main
