### ISSUE TITLE
Read-model operations error: build MyAggregateList Error: Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by David-Lio** [reimagined/resolve#1978]
**Describe the bug**
There is an error when using the @resolve-js/readmodel-mysql adapter and running the app, it shows an error with the "Read-model operations error: build MyAggregateList Error: Can't add new command when connection is in closed state" text

**To Reproduce**

1. Create a new resolve project `npx create-resolve-app my-awesome-app`
2. Change the config.dev.js  to use the readmodel-mysql
3. Install `@resolve-js/readmodel-mysql` package
4. Use `npm run dev` command
5. See error

- ReSolve Version 0.31.5

**Comment by FreeSlave** [comment]
Thanks for reporting. We've managed to reproduce the issue and it's probably related to the latest changes to the bootstrap process. Currently we don't run any automated tests for mysql and focus on postgresql mostly.
You may try using 0.31.4 or switch to postgresql. I would not recommend using mysql adapters as they are outdated.

**Comment by David-Lio** [comment]
It works well after changing the @resolve-js/scripts version to 0.31.4
