### ISSUE TITLE
Add an option to specify hostname for running app in dev mode

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [reimagined/resolve#2024]
**Is your feature request related to a problem? Please describe.**
I have several network adapters on my machine. I'd like to share an url of the launched application. The `npm run dev` command uses randomly choosed IP address. I want to specify IP of the particular network (including CDN url)

**Describe the solution you'd like**
Specify a hostname with which app will be launched

**Comment by max-vasin** [comment]
Yes, this is currently cannot be configured. I'll register feature request.

**Comment by MrCheater** [comment]
**Additional context:**
* hardcode: https://github.com/reimagined/resolve/blob/dev/packages/runtime/runtime/src/local/start-express.js#L8 and https://github.com/reimagined/resolve/blob/dev/packages/tools/scripts/src/open_browser.js#L15
* field "host" does not exists https://github.com/reimagined/resolve/blob/dev/packages/tools/scripts/configs/schema.resolve.config.json
* custom hostname CDN Url https://github.com/reimagined/resolve/blob/30499a8c69d4974adc0aabd82af4af0a2d82bf24/examples/js/personal-data/config.cloud.js#L32
