### ISSUE TITLE
No necessary data in command if its execution is failed

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#203]
I want to handle 3 steps of command execution in reducer. That's what I do:
```js
export default (state = Immutable({}), action) => {
  switch (action.type) {
    case '@@resolve/SEND_COMMAND': {
      switch (action.command.type) {
        case 'createStory': {
          return action.status.error // or action.command.error
            ? // error handling
            : // command sending handling
        }
        default: {
          return state;
        }
      }
    }
  }
};
```
The first problem is that if error is thrown, `action.command` is excluded so I can't detect whether I handle the `createStory` command error or not.
The second problem is that if there is not error, `action.status` is not included to the action. So I need to have to checks - action.status and then action.status.error to put error.

Here is solutions as I see them:
1. Do not exclude command first 'cause it contains important information
2. Use action.command to put error not to add new fields that leads to extra conditions.

**Comment by MrCheater** [comment]
https://github.com/reimagined/resolve/blob/ab9c6bf1e9ff5074bc4f856d7a6174e0c77ba4ca/packages/resolve-redux/src/send_command_middleware.js#L23
