### ISSUE TITLE
"Step-by-Step Tutorial" is unfriendly for steps reproducing.

### ISSUE THREAD

**Issue by dositec** [reimagined/resolve#2093]
I tried to repro the steps by the following link: https://reimagined.github.io/resolve/docs/tutorial/
And found that after steps execution I had results which is not equals for results in the docs.

For example: I didn't have "event-store.db" but I had "storage.db"
Also using of code snippets with curl tool using looks very unfriendly for users of Windows OS.

**Comment by EugeniyBurmistrov** [comment]
Hi! Lately, the tutorial has gone through some major enhancements that you can review in [this PR](https://github.com/reimagined/resolve/pull/2068). We've made an effort to make the tutorial shorter and easier to follow. Some of the problems you mentioned have been fixed as a part of this PR. 
As for all the *curl* inputs - we have tried to povide an aletrnative for them by describing how to write tests for every new piece of functionality in the training application. Although, the *curl* inputs are still there on a sepearete tab.

**Comment by EugeniyBurmistrov** [comment]
We updated the tutorial to fix the issues you described. We also replaced *curl* input samples with reasonable alternatives throughout the documentation.
