### ISSUE TITLE
Custom read-model does not start

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#2095]
**Describe the bug**
Our custom elasticsearch read-model does not start after the app is deployed to the cloud. No errors in the app logs.
After ```read-model reset``` it runs as expected.

**Screenshots**
```read-model list``` CLI command returns
```
NAME                 STATUS               SUCCESS EVENT                               FAILED EVENT         LAST ERROR
Search               skip                 N\A                                         N\A                  N\A  
```
- ReSolve Version 0.32.0

**Additional context**
App deployed with existing, not empty event store (```--event-store-id``` option)

**Comment by MrCheater** [comment]
Fixed in version 0.33.0 
![Screenshot from 2021-11-09 15-15-03](https://user-images.githubusercontent.com/5055654/140925847-e079a917-f954-4c08-9cf9-f074eb8991c0.png)
