### ISSUE TITLE
WARN Inline procedure execution failed for reason DependencyError

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#2097]
**Describe the bug**
Strange warnings in logs.
`2021-10-29T08:21:44.575Z: 2021-10-29T08:21:44.575Z      064c0eca-9708-4c26-a687-17de6c4a12fa    WARN    Inline procedure execution failed for reason: {"name":"DependencyError","code":null,"message":"undefined","stack":"DependencyError\n    at Object.get (PROC-UserStats:11:104431)\n    at PROC-UserStats:3:5102\n    at f (PROC-UserStats:3:30738)\n    at Generator._invoke (PROC-UserStats:3:30491)\n    at Generator.next (PROC-UserStats:3:31101)\n    at e (PROC-UserStats:3:36141)\n    at a (PROC-UserStats:3:36352)\n    at i.<anonymous> (PROC-UserStats:3:36411)\n    at new i (PROC-UserStats:3:10419)\n    at PROC-UserStats:3:36292"}`

- ReSolve Version 0.32
- "@resolve-js/readmodel-postgresql": "0.32.0",
EXPERIMENTAL_INLINE_DB_EVENT_LOAD=1

**Comment by IhostVlad** [comment]
This warning shows that read-model projection is running with Postgresql adapter with PLV8 support, but have some issues which does not allow run it in fast PLV8 mode.
For instance, fast PLV8 projection should not import native npm-packages or build-in modules (like `import fs from "fs"`), and should not perform runtime import (like `const myModule = await import("my-module")`).
So there is no permanent problems with read-model, it will continue building, but in slow non-plv8 mode. Of course, this limitations should be reflected in documentation.

**Comment by EugeniyBurmistrov** [comment]
We have updated the warning message so it clearly states the issue and added a [troubleshooting article](https://www.resolve.sh/docs/troubleshooting/#an-application-starts-but-an-plv8-related-warning-appears-in-logs) with details.
