### ISSUE TITLE
[resolve-scripts] Can't parse initial state, SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by Vasiliy-Lavrov** [reimagined/resolve#212]
I created [storage.json](https://github.com/reimagined/resolve/files/1267054/storage.json.zip) for [Hacker News Demo](https://github.com/reimagined/hacker-news-demo/commit/6133dfb78968fcf19d2f301b851b5ef83b9caa7c)

**Comment by IhostVlad** [comment]
Done in https://github.com/reimagined/resolve/pull/214
