### ISSUE TITLE
Error messages should have more information

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#265]
You have the 'Some of event mandatory fields (*field1*, *field2*) are missed' message everywhere. It's better to write concrete fields that are missed with the entire list: if I missed one field, write about it, if two ones - write about both of them.

**Comment by timbset** [comment]
The example is taken from resolve-es. Maybe the same issue is with other packages.

**Comment by IhostVlad** [comment]
https://github.com/reimagined/resolve/pull/302
