### ISSUE TITLE
The lib is not friendly to errors

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#293]
Add good readable error output if user does something wrong

**Comment by timbset** [comment]
Add error throwing to the `extendExpress` function. Nothing is shown in console - it still works as everything is ok. But all the logic I added to express extension is not applied.

**Comment by timbset** [comment]
If format of some configs is incorrect, there is no any info about it or some strange inner errors are shown (like `reduce of undefined`)

**Comment by IhostVlad** [comment]
Work continued in https://github.com/reimagined/resolve/issues/320 issue

**Comment by IhostVlad** [comment]
Most issues above are fixed, some work about improvement for visual error representation will be reflected in #320 issue
