### ISSUE TITLE
Aggregate snapshot

### ISSUE THREAD

**Issue by davidnussio** [reimagined/resolve#404]
Would be wonderful if will be possible to store aggregate state with a snapshot strategy and the loading will start from snapshot and apply the rest of events (where snapshot.aggregateVersion < event.aggregateVersion)

After using axon framework in java I always hope to find a project like this in Javascript! 

Good job, thanks for sharing!

**Comment by superroma** [comment]
First issue!

Thanks for suggesting, we are considering snapshots, and i'm sure eventually will implement them, but GregYoung adviced to measure first. So far we  did not encountered a case when we need them, our average hardware (AWS t2-micro) can apply 20-70K of events/sec, and we never had an aggregate in apps we did with even 1K of events.

So do you have a real use case for a need of snapshot?

**Comment by davidnussio** [comment]
No real use case. Axon support this functionality but we actually have been in production for four years and we have never used this feature.

I think your project is very interesting thing and I'm collecting information about the project, comparing it to what we know. I just found this project and am studying the resolve-* packages...

Thank you,
David

**Comment by superroma** [comment]
Ok, we'll keep this in mind, but wait for real world scenario.
