### ISSUE TITLE
It is impossible to specify resolvers for field of type

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#406]
Here is a documentation from the Apollo lib: https://www.apollographql.com/docs/graphql-tools/resolvers.html. There is a resolvers description. All the GraphQL resolvers are based on the types and their fields resolvers. The root type for queries is Query. But this type is hidden in the reSolve resolvers that is wrong. Here is an example of using Apollo resolvers, so I expect to see the same in reSolve:

Schema:
```js
const schema = `
  type Employee {
    id: ID!
    name: String!
    company: Company!
  }
  type Company {
    id: ID!
    name: String!
    employees: [Employee!]
  }
  type Query {
    company(id: ID!): Company
  }
`;
```

Resolvers:
```js
const resolvers = {
  Query {
    company: (_, { id }) =>
      read('company', id) // Async getting of the company by id
  },
  Company {
    employees: company =>
      read('employeesByCompanyId', company.id) // Async getting of the employee list by company id
  }
};
```

I need this because I want to load employees only if I require them in the query. Else I don't want the company resolver not to spend time for getting of employees.

**Comment by IhostVlad** [comment]
> not to spend time for getting of employees
Can erraticly seem that the specified information is connected to questions of productivity and optimization - it is quite misleading.
It can be the useful improving influencing only a possibility of specifying of concrete types instead of anonymous types. It does not influence the number of appeals to a DB in any way.
