### ISSUE TITLE
Pass JWT directly

### ISSUE THREAD

**Issue by IhostVlad** [reimagined/resolve#472]
Exclude getJwtValue functionality
Provide pure JWT token into command handlers and projection functions.
Extract JWT verification into package `resolve-auth`

**Comment by superroma** [comment]
> Extract JWT verification into package resolve-auth
Why? Put it somewhere that aware of secret on the server.

**Comment by superroma** [comment]
Also, JWT should be available only at the Command and Query handlers - to put user context into requests. Not on client of course

**Comment by IhostVlad** [comment]
@superroma It's clear about Command & Query handlers and client side. But what about:
> Put it somewhere that aware of secret on the server.
If Command & Query handlers will receive only raw JWT token, they should contain copy+paste code in every handler, which will verify the token and extract data from it.
So, there should be a function, which will encapsulate JWT verification and data extraction. Where should it be located?

**Comment by superroma** [comment]
> So, there should be a function, which will encapsulate JWT verification and data extraction. Where should it be located?

Somewhere near users of this function, why new package? For instance in resolve-command, and in resolve-query
