### ISSUE TITLE
Pass JWT in the header, not cookie.

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#475]
From [JWT introduction](https://jwt.io/introduction/):
> Whenever the user wants to access a protected route or resource, the user agent should send the JWT, typically in the Authorization header using the Bearer schema. The content of the header should look like the following:
> 
> Authorization: Bearer <token>

Is it possible for us to use the same standard schema? We are using cookies currently - which makes our server less usable without our client. Since we provide both command and query wrappers in resolve-redux, why not use standard header?

**Comment by IhostVlad** [comment]
> Is it possible for us to use the same standard schema?

Most likely, no, at least in current `resolve-scripts` implementation. Anyway JWT token should be store on client side, to be passed with further command & query requests.

Cookies provide default way to store data on client side. Data also can be stored in DOM storage, but it causes more complicated code in `resolve-redux` and `appolo-graphql` on client side, which should add custom HTTP header (`Authorization: Bearer`) for any request.
Also, special route will be needed for receiving JWT token ( https://tools.ietf.org/html/rfc6750#page-10  )

Combination with passport authorisation providers looks not well for supposed circumstance.
