### ISSUE TITLE
Update resolve-redux documentantion

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#534]
There are some breaking changes in resolve-redux. For examle, `connect()` is no longer exist. Please update the package documentation.

**Comment by TatyanaRyzh** [comment]
Hello!

Thank you for a request, it's very important for us. This issue is fixed in [**0.7.2 version**](https://github.com/reimagined/resolve/releases/tag/V0.7.2). 

Please, update the reSolve packages for your application.
