### ISSUE TITLE
Crash on React Native

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#535]
![screenshot_20180323-130736](https://user-images.githubusercontent.com/36633600/37824363-5f161650-2e9d-11e8-863d-bd1f51924a03.jpg)
resolve 0.7.1
expo 25.0.0
react-native 0.52.0

**Comment by IhostVlad** [comment]
Most likely that `react-native` supports by default only Ecmascript-262 version 5.1, but `resolve` is written on ES8 latest version. Just include `babel-polyfill` and everything will work.
Currently, that polyfill is absent: https://github.com/zloirock/core-js/blob/master/modules/es6.object.set-prototype-of.js
It's default part of ES6 spec: http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots-setprototypeof-v

**Comment by alexslavr** [comment]
Fixed with: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-set-prototype-of-to-assign. 

> ES8 latest version

I think it's not good for compatibility with `react-native`

Just for information, used by default `babel-preset-react-native` supports most of ES6-ES7 features: https://github.com/facebook/react-native/tree/master/babel-preset

**Comment by IhostVlad** [comment]
`Resolve` library team solved that it's not bug for our library per se. If you sure that provided issue caused by real bug `resolve` - feel free to contact us, but provided stack trace has no `resolve` frames or functions.
