### ISSUE TITLE
View models reactivity does not work

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#536]
Version 0.5.4. I am migrating the app from the asterisk aggregateId to real aggregateIds in view models. So to minify risks of spending the time I mix these to variants of view model aggregateId. But unexpectedly the reactivity of real aggregateId does not work. After debugging I found out that real aggregateId subscriptions are ignored if the asterisk is specified. It is a wrong behavior. Also, I had no notification that I do something wrong if we consider this scenario as it is correct.

After deleting the asterisk aggregateId, everything works.

**Comment by TatyanaRyzh** [comment]
Thank you for a response! We've fixed it in 0.8.1 version. 

Please, feel free to take a look at the latest [reSolve 0.9.0](https://github.com/reimagined/resolve/releases/tag/V0.9.0) version and contact us if you have any questions.
