### ISSUE TITLE
Implement $in Read Model API

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#573]
Use case:
I have collections of orgunits and users. Every orgunit has an array of user ids inside. I need to get orgunit with all included users. Users should be sorted by name.
Now:
I need to make N requests for each user id and then sort an array.
Expected:
I want to use $in operator with user ids array to make only one request. Also I can specify sort criteria in request.

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your proposal of new API method sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your idea with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
