### ISSUE TITLE
Possibility to use env variables in resolve.config.json

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#581]
I need to customize the storage and the port params in production mode. The common case is to use env variables but I have no possibility to add them. I expect to see something like that:
```json
{
  "port": "$PORT"
}
```
It leads to getting the 'port' param value from `process.env.PORT`.

**Comment by timbset** [comment]
Also I need to have possibility to add JSON from env variables, e.g. storage options
```
> npx STORAGE_OPTIONS="{ url: \"mongodb://localhost:27017\", collectionName: \"Events\"" } yarn dev
```

**Comment by IhostVlad** [comment]
Done
