### ISSUE TITLE
The storage config param has some issues

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#583]
- Because of having some types of storage (see https://github.com/reimagined/resolve/issues/582) it is better to use the `eventStorage` option name
- Use short version of adapter (e.g. `mongo` to use `resolve-storage-mongo` package)
- Use the `collectionName` option for the `mongo` adapter instead of `collection`
- Extract database name from the `url` option and put it to the `dbName` option

Before:
```
"url": "mongodb://localhost:27017/MyDatabase"
```
After:
```
"url": "mongodb://localhost:27017,
"dbName": "MyDatabase"
```

**Comment by MrCheater** [comment]
Steps:
1. Update npm package "mongodb" to 3.0.7
2. Fix inner BC 
```js
// Before:
"url": "mongodb://localhost:27017/MyDatabase"

// After:
"url": "mongodb://localhost:27017,
"dbName": "MyDatabase"
```

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your scenario with those config settings sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your suggestion with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
