### ISSUE TITLE
Client source code changing leads to full server restart

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#588]
I have a large read model that is being built for a long time. I just change something in client and wait until my read model is built again. It is annoying. I expect splitting of hot reload - one for server side and one for client or isomorphic side.

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your scenario sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your proposal with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
