### ISSUE TITLE
Reactive read model connector mutates state

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#600]
I have a complex object got from server. Its structure is:
```
{
  orgUnit: {
    objectives: [{ id: 'id1' }, { id: 'id2' }]
  }
}
```
After sending command I get an update response that reactively updates this state. But when I check `state.orgUnit.objectives` with previous one after response, these two arrays are equals by reference. This means that array is modified instead of creation of the new one. Because of this a cannot update component childs - they check, that nothing is changed (references are equal) so render function is not called.

**Comment by IhostVlad** [comment]
Done, will be shipped in resolve 0.11.0 version
