### ISSUE TITLE
There is no way to change read model variables to fetch new data

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#602]
I use read model connector with some variables. After some manipulations inside the wrapped component I want to change variables and fetch data with them. Now the only way is to pass these variables to the parent component. But this is not a good solution. I expect something like `props.refetch({ var: 1 })` in the wrapped component.

**Comment by IhostVlad** [comment]
Read model connectors works different way than Apollo, so such approach will not work. Connector just provides automatical data retrieving from read-model resolver by read model name, resolver name and custom arguments. These values can be passed via literals or `ownProps`, provided from parent component. Connector does not care, which way those values had been affected - if changed, fresh data from server will arrive. Refetch pattern is not applicable for current lifecycle.
