### ISSUE TITLE
The 'port' config option is ignored

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#617]
I specified the 'port' option using `resolve.config.json` and specified the 'PORT' env variable on an app start. The second one is unexpectedly rewrite the first one

**Comment by TatyanaRyzh** [comment]
Hi timbset,
 
We've reproduced your scenario of 'port' config option ignoring and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)
