### ISSUE TITLE
Aggregate name is not specified for event automatically

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#622]
I use following code for aggregates:
```
{
  createItem(state, { aggregateId, payload: { number } }) {
    return {
      type: 'itemCreated',
      aggregateId,
      payload: { number }
    };
  }
}
```
I expect to see following event:
```
{
  type: 'itemCreated',
  aggregateName: 'Item',
  aggregateId,
  aggregateVersion: 1,
  payload: { number: 10 },
  timestamp: 1526365184075
}
```
Now I have something the same excluding aggregateName. It is missed. I expect that it will be done it automatically.

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your suggestion sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your idea with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
