### ISSUE TITLE
Remove 'add-module-exports', 'trahsform-export-default' plugins from resolve-scripts dependencies

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#624]
Babel plugins 'add-module-exports', 'trahsform-export-default' are incompatible with react-native bundler and expo

**Comment by MrCheater** [comment]
https://github.com/59naga/babel-plugin-add-module-exports/issues/51
> [ @lijunle ] My personal suggestion is not to support future babel versions.

Coming soon Babel 7. So we will remove these dependencies
