### ISSUE TITLE
Aggregates and read models are included to client bundle

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#627]
This is a server side so I do not expect to see it in bundle. It is a security problem.

**Comment by TatyanaRyzh** [comment]
Hi timbset,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)
