### ISSUE TITLE
Aggregate id should be validated to prevent potential problems

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#628]
The typical problem is forgetting about arguments order. E.g. I need to call `actions.createUser(aggregateId, { email })`, but I use `actions.createUser({ email })`. It does not lead to error. But in this case the aggregate id type is not a string. It must be checked and error should be thrown if it is necessary.

**Comment by TatyanaRyzh** [comment]
Hi timbset,

We've reviewed your Pull Request #651  and will merge it as soon as possible. Once it's done, we will let you know here.

Thank you very much for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)
