### ISSUE TITLE
[readmodel-adapter-mysql] Cyrillic text in "string" column causes an error

### ISSUE THREAD

**Issue by DmitryBogomolov** [reimagined/resolve#632]
If column is declared with `string` type and then string containing Russian letter passed - adapter fails.
(It can be walked around by declaring column with `json` type).

**Comment by TatyanaRyzh** [comment]
Hi DmitryBogomolov,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by IhostVlad** [comment]
Done! Will be shipped in following release
![image](https://user-images.githubusercontent.com/14352827/41591394-3f6d6140-73c2-11e8-94a1-230f90d8b88b.png)

**Comment by TatyanaRyzh** [comment]
Fixed in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)
