### ISSUE TITLE
It is hard to manipulate configs in different environments

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#639]
I think the best solution would be to provide the 'config' option where I can specify the file path to it. It will help me to use multiple different configs that are not committed to VCS. Now I need modify the `resolve.config.json` file manually and take care to not commit these changes.

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your proposal sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your suggestion with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Implemented in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)

**Comment by TatyanaRyzh** [comment]
Implemented in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
