### ISSUE TITLE
Necessity to extract meta data of aggregates and read models

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#644]
Now aggregates and read models are included to the client bundle. This was made for having actions created depending to some meta data (command names, event names, etc.). It is better to implement some script that extract all info to the different files that are included to the client bundle, without extra source code. You can start this scripts for example on pre-commit. It will increase an app security (in aggregate I can implement password hashing algorithm and I don't want to share it in public resources).

**Comment by TatyanaRyzh** [comment]
Hi timbset,

Your scenario sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your suggestion with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Implemented in [V0.12.1](https://github.com/reimagined/resolve/releases/tag/V0.12.1)
