### ISSUE TITLE
There is no sever side in newly created app

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#655]
**Describe the bug**
After running `npx create-resolve-app`, resulting new app has no server-side folders and files. I don't need code there, but I need placeholders, so I don't have to dig for this info somewhere else.

**To Reproduce**
`npx create-resolve-app`

**Expected behavior**
I want to open an app and start coding, not trying to reinvent a server folder structure.

**Comment by TatyanaRyzh** [comment]
Hi superroma,

Your scenario sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your idea with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Implemented in [0.13.0](https://github.com/reimagined/resolve/releases/tag/V0.13.0)
