### ISSUE TITLE
resolve-redux: connectReadModel, connectViewModel, etc should distinct backend errors

### ISSUE THREAD

**Issue by max-vasin** [reimagined/resolve#664]
**Describe the bug**
connectReadModel invocation causes infinite retry loop on any backend server error

**Expected behaviuor**
Except HTTP 408 (request timeout), a redux action with specified error should be generated and handled by reducer(s) to allow client code to decide what to do (render auth component, show error page). Also there must be a way to re-request read/view model data, when the situation resolved.

**Comment by TatyanaRyzh** [comment]
Hi max-vasin,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!
