### ISSUE TITLE
Improve usability of $resolve.rootPath variable

### ISSUE THREAD

**Issue by DmitryBogomolov** [reimagined/resolve#668]
**Describe the bug**

Let's say there is the following url:
```javascript
const url = `/${$resolve.rootPath}/static/image.png`
```

If bundle is built with empty `rootPath` then `url` is `//static/image.png` which is incorrect (if `rootPath` is non empty then `url` is fine).
If preceding `/` is removed from code then situation is reversed; `rootPath` non is empty - incorrect `url`, `rootPath` is empty - fine.

**Expected behavior**

Looks like `/` should be part of `$resolve.rootPath` variable - so that default (empty value) is empty string and non default is `/some-path`. Then any url is to be declared as follows:
```javascript
const url = `${$resolve.rootPath}/static/image.png`
```

**Comment by DmitryBogomolov** [comment]
Same applies for `$resolve.staticPath`.

**Comment by ralkov** [comment]
Hi Dmitry,

We've reproduced your scenario and will fix it as soon as possible.

Thank you for helping us improve reSolve!
