### ISSUE TITLE
unsubscribeReadModel shouldn't be called if readmodel is not reactive

### ISSUE THREAD

**Issue by iokhotnikov** [reimagined/resolve#670]
**Describe the bug**

If readmodel is not reactive (`isReactive: false`) client send requests to unsubscribe from readmodel updates

**Expected behavior**
The `unsubscribeReadModel` shouldn't be called if readmodel is not reactive

**Comment by TatyanaRyzh** [comment]
Hi iokhotnikov,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [0.13.0](https://github.com/reimagined/resolve/releases/tag/V0.13.0)
