### ISSUE TITLE
Resolve.config.json have inconsistent options

### ISSUE THREAD

**Issue by TatyanaRyzh** [reimagined/resolve#671]
**Describe the bug**
The aggregates, readModels and viewModels config options are described in resolve.config.json:

```json
aggregates: [],
viewModels: [],
readModels: []
```
But `sagas` and `auth` don't have such style:

```json
"auth": {
    "strategies": "auth/index.js"
 },
sagas: "common/sagas/index.js"
```

**Expected behavior**
```json
"auth": [],
"sagas": []
```

**Comment by IhostVlad** [comment]
Since version 0.14.0, `resolve.config.json` is not supported anymore. See [documentation](https://github.com/reimagined/resolve/blob/master/docs/API%20References.md#configuration) to refer how to configure `resolve` application now.
