### ISSUE TITLE
npm run dev throw error on regExp

### ISSUE THREAD

**Issue by thoomasbro** [reimagined/resolve#673]
Hi,
After several tries, I'm still not able to run  todo example.

After yarn create resolve-app todo-example -e todo 
and npm run dev
SyntaxError: Invalid regular expression: /(process\.env\.(?:\w|_)(?:\w|\d|_)+?)(\s*(?:,|})(?=(?:[^"]*(?<!\\)"[^"]*(?<!\\)")*[^"]*$))/: Invalid group
    at Object.<anonymous> (/Users/me/resolve/todo-example2/node_modules/json-env-extract/src/index.js:6:16)

I tried npx and yarn several times, in clean directories.

**To Reproduce**
1. yarn create resolve-app todo-example -e todo
2. cd ./todo-example2
3. npm run dev

**Desktop (please complete the following information):**
 - OS: OSX 10.11.6
 - npm 5.6.0
- node 8.9.4
- yarn 1.6.0
- resolve 0.12.1

**Comment by TatyanaRyzh** [comment]
Hi thoomasbro,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [0.12.3](https://github.com/reimagined/resolve/releases/tag/V0.12.3).
