### ISSUE TITLE
redundant  devDependencies

### ISSUE THREAD

**Issue by iokhotnikov** [reimagined/resolve#676]
For example:
https://github.com/reimagined/resolve/blob/master/packages/readmodel-adapters/resolve-readmodel-mysql/package.json#L40

Looks like there are redundant dependencies:

```json
    "jest": "^23.0.1",
    "chai": "^4.1.2",
    "sinon": "^5.0.10",
```

If you use jest it's redundantly to use chai and sinon
If you use chai and sinon it's redundantly to use jest

**Comment by TatyanaRyzh** [comment]
Hi iokhotnikov,

Your proposal sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your idea with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
