### ISSUE TITLE
Change of resolve.config.json does not restart application in mode `npm run dev`

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#679]
**Describe the bug**
Change of resolve.config.json does not restart application in mode `npm run dev`

**To Reproduce**
1. `npm run dev`
2. Update resolve.config.json
3. No reaction

**Expected behavior**
Restart application when config is changed

**Desktop (please complete the following information):**
 - Windows/Linux/MacOS
 - Node
 - 8.11.3

**Comment by TatyanaRyzh** [comment]
Not reproduced in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
