### ISSUE TITLE
Non-informative error is thrown if read model name is incorrect

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#682]
I'm trying to request data from read model so I specify read model name and resolver name. If I specify an incorrect read model name, there is a strange error:
```
TypeError: Cannot read property 'read' of undefined
    at _callee$ (D:\Repositories\okrserver\node_modules\resolve-scripts\dist\runtime\server\execute_read_model_query.js:36:1)
...
```
Here I expect to see what's wrong (e.g. `There is no 'myReadModel' read model`)

**Comment by TatyanaRyzh** [comment]
Fixed in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
