### ISSUE TITLE
No example provided for storage adapters & snapshot adapters

### ISSUE THREAD

**Issue by thoomasbro** [reimagined/resolve#706]
Provided examples are very detailed to test the project, but documentation lacks some details regarding storage adapters for events and snapshot adapters

Some examples using resolve-storage-mongo & resolve-readmodel-mysql will be appreciated

or may be just detailing the doc a bit more..
Thanks again for your work.

**Comment by IhostVlad** [comment]
Hi, Thomas!
We are continuously working on documentation improvement. In future releases there will be more examples, including `read-model` and `storage` adapters.
Note that all provided adapters in `resolve` repository are interchangeable inside same category. For example, default adapter `resolve-readmodel-memory` can be replaced in config to `resolve-readmodel-mysql` or `resolve-readmodel-mongo` without any nessesary changes performed in `read-model` `projection` and `resolvers` source code in your application.
Of course, every adapter has it's own specific options. Now you can examine them at https://github.com/reimagined/resolve/blob/dev/packages/readmodel-adapters/resolve-readmodel-mongo/src/implementation.js#L9 and https://github.com/reimagined/resolve/blob/dev/packages/readmodel-adapters/resolve-readmodel-mysql/src/implementation.js#L10 respectively. But documentation will be improved.
Thank for your feedback!

**Comment by TatyanaRyzh** [comment]
In case we implement it in a future release, we will let you know here. Thank you!
