### ISSUE TITLE
Uncaught Reference Error: WeakMap is not defined

### ISSUE THREAD

**Issue by MrCheater** [reimagined/resolve#711]
**Describe the bug**
Uncaught Reference Error: WeakMap is not defined

**Expected behavior**
```js
// resolve.config.json
{
  // ...
  polyfills: [
    "core-js/modules/es.weak-map",
    "core-js/features/array/from",
    "core-js/features/array/flat",
    "core-js/features/set",
    "core-js/features/promise"
  ]
  // ...
}
```

**Desktop (please complete the following information):**
 - Android
 - React-narive
 - 0.55.4

**Comment by TatyanaRyzh** [comment]
Fixed in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
