### ISSUE TITLE
Clarify roles of projections between aggregate, readmodel and viewmodel

### ISSUE THREAD

**Issue by thoomasbro** [reimagined/resolve#719]
Exploring the documentation and the different examples & tutorials, it's not clear to me what are the different roles of projections between aggregate, readmodel and viewmodel.

Looking at the HN example, I understand that the readmodel is computed only on the server, whereas viewmodel is used to sync redux state and used on both client and server sides. Am I right ? And what about the aggregate projection ?

It could be great if it was a bit more detailed.
Thanks !

**Comment by thoomasbro** [comment]
Thanks for the detailed answer.
So read-models are executed only on server side, right ?
What is resolve-cloud ?

**Comment by IhostVlad** [comment]
Hi @thoomasbro 

> So read-models are executed only on server side, right ?

Yes, with one exception. If you are using reactive read-models, resolvers result can be automatically updated on client side, when some projection function had processed new event, which affects resolver result. Remind that reactive read-models are not supported in resolve-cloud, use only on own risk.

> What is resolve-cloud ?

It's commercial paid version of `resolve` in cloud. Now it's in early alpha and so unavailable for public.

Thanks

**Comment by TatyanaRyzh** [comment]
Hi thoomasbro,

Your proposal of clarifying the roles in our documentation for read-models, view-models and aggregates sounds interesting. Thank you for sharing it with us. We are always open to our users' feedback.

I'll share your suggestion with the team. In case we implement it in a future release, we will let you know here.

Thank you for helping us improve reSolve!
