### ISSUE TITLE
[resolve-script] Build results should contain data from processed resolve.config.json

### ISSUE THREAD

**Issue by DmitryBogomolov** [reimagined/resolve#724]
A particular example - *jwtCookie* section. There should be a way to access this setting (without using `import xxx from '$resolve.xxx'` as it would be executed without *resolve-scripts*).

It would be suitable if there is *config.json* file inside *dist* folder which contains process data from *resolve.config.json*.

**Comment by TatyanaRyzh** [comment]
Hi DmitryBogomolov,
 
We've reproduced your scenario and will fix it as soon as possible.
 
Thank you for helping us improve reSolve!

**Comment by TatyanaRyzh** [comment]
Fixed in [0.14.0](https://github.com/reimagined/resolve/releases/tag/V0.14.0)
