### ISSUE TITLE
Too many WARNINGS while example install

### ISSUE THREAD

**Issue by TatyanaRyzh** [reimagined/resolve#735]
**Describe the bug**
When I want to install the example, I see too many warnings

**To Reproduce**
* 0.13.2 resolve version
* `npx create-resolve-app example -e hello-world`

**Expected behavior**
I want see clear console with only progress of installation

**Screenshots**
![warnings](https://user-images.githubusercontent.com/19663260/43953148-cadc1ecc-9ca0-11e8-982f-8c2d03dce453.png)

**Comment by IhostVlad** [comment]
Fixed in [0.14.2](https://github.com/reimagined/resolve/releases/tag/V0.14.2)
