### ISSUE TITLE
Disable explicit `in` operator for storage adapters

### ISSUE THREAD

**Issue by iokhotnikov** [reimagined/resolve#739]
For inMemory and MongoDB readmodel adapter it is possible to write criteria like { ids: 'some-id' } for array schema and it works fine. 
But for MySQL adapter there is not explicit `in` operator for such criteria.

In the result there are 2 different builded readModels for inMemeory and MySQL adapters.

**Comment by IhostVlad** [comment]
Described effect caused since automatic array matching in `mongodb` and `nedb` databases - https://docs.mongodb.com/manual/tutorial/query-arrays/#match-an-array
Such option is not planned in read-model query API, so it will be fixed by disabling implicit array matching

**Comment by IhostVlad** [comment]
Fixed in https://github.com/reimagined/resolve/releases/tag/V0.14.2
