### ISSUE TITLE
Can't run resolve todo example app with yarn if Storybook installed

### ISSUE THREAD

**Issue by krutilin** [reimagined/resolve#751]
Recieve error on build:
ERROR in multi ./node_modules/resolve-scripts/dist/core/alias/$resolve.hotModuleReplacement.js
Module not found: Error: Can't resolve 'val-loader' in '/Users/ykrutilin/Desktop/resolve-todo-example'
 @ multi ./node_modules/resolve-scripts/dist/core/alias/$resolve.hotModuleReplacement.js hmr.js[0]

1. npx create-resolve-app resolve-todo-example -e todo
2. npm i -g @storybook/cli
3. cd resolve-todo-example
4. getstorybook
5. rm -rf node_modules/ dist/
6. yarn
7. yarn dev

**Expected behavior**
Run TODO app.

**Desktop (please complete the following information):**
- Mac and Ubuntu
- yarn 1.9.4

**Comment by krutilin** [comment]
Additional info:

By default, storybook uses the stable version, which does not work with babel 7. Storybook would not start at all and resolve TODO app too.
    "@storybook/react": "^3.4.10",
    "@storybook/addon-actions": "^3.4.10",
    "@storybook/addon-links": "^3.4.10",
    "@storybook/addons": "^3.4.10"

you can install latest using following config. Storybook will start (yarn storybook) but resolve TODO app will fail.
    "@storybook/react": "^4.0.0-alpha.16",
    "@storybook/addon-actions": "^4.0.0-alpha.16",
    "@storybook/addon-links": "^4.0.0-alpha.16",
    "@storybook/addons": "^4.0.0-alpha.16"

**Comment by MrCheater** [comment]
Fixed in version 0.18.14
