### ISSUE TITLE
Building hacker-news projection with readmodel-adapter-mysql adapter is very slow

### ISSUE THREAD

**Issue by IhostVlad** [reimagined/resolve#810]
Building hacker-news projection with readmodel-adapter-mysql adapter is very slow
When using mongodb adapter, projection had been build approximately tens times faster
Profiling log https://gist.githubusercontent.com/IhostVlad/81c5f8057945d2708452f1c5d3186a4d/raw/943a66929e6471f0189a540180093b5664965a36/prof.log

**Comment by MrCheater** [comment]
Fixed in version 0.20.1
