### ISSUE TITLE
Wrong command execution in create-resolve-app

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#826]
**Describe the bug**
In process of an app creation I see the following error:
```
Copy example
'cp' is not recognized as an internal or external command,
operable program or batch file.

37 File(s) copied
```
This does not lead to creation failure - creation is finished correctly and started app works well.

**To Reproduce**
Create resolve app

**Additional context**
The `create-resolve-app` version: 0.17.2
OS: **Windows**

**Comment by MrCheater** [comment]
Fixed in version [0.18.0](https://github.com/reimagined/resolve/releases/tag/V0.18.0)
