### ISSUE TITLE
Create-resolve-app: running failed task does not lead to bash command failure

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#832]
**Describe the bug**
The `run` task is always finished successfuly in the app created by `create-resolve-app`.

**To Reproduce**
Create an app and run some failing task or look at the `run` script source code.

**Expected behavior**
I expect to change following code
```js
})().catch(error => {
  // eslint-disable-next-line no-console
  console.log(error)
})
```
to
```js
})().catch(error => {
  // eslint-disable-next-line no-console
  console.log(error)
  process.exit(1)
})
```

**Additional context**
As a motivation, I have a queue of bash tasks and stop execution a queue if one of tasks is failed. This task must be failed but it don't and all other tasks work with incorrect environment.

**Comment by MrCheater** [comment]
Fixed in version [0.18.0](https://github.com/reimagined/resolve/releases/tag/V0.18.0)
