### ISSUE TITLE
Impossible to secure view model data from unauthorized user correctly

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#902]
I have a view model state and authentication. I need to return serialized data if user is authorized and 'null' if not. User jwt is passed to the 'serializeState' function that I can specify for view model where I can check if user is authorized:
```js
const serializeState = (state, token) => {
  try {
    const data = jwt.verify(token, JWT_SECRET)

    if (data && data.userId) {
      return JSON.stringify(state)
    }
  } catch (e) {}

  return JSON.stringify(null)
}
```
The problem is that I use snapshot adapter to store view model state and it uses this serialize function at the same time but without jwt because it is an internal mechanism, not a user. The only way to indentify whether user request leads to this call or some internal mechanism is to check arguments count:
```js
const serializeState = (...args) => {
  const [state, token] = args

  if (args.length === 1) {
    return JSON.stringify(state)
  }

  try {
    const data = jwt.verify(token, JWT_SECRET)

    if (data && data.userId) {
      return JSON.stringify(state)
    }
  } catch (e) {}

  return JSON.stringify(null)
}
```
It is hard to understand for common user (but this is a user code). It is better to use some request handler that is called only for user data request and that returns the result of serializer. I'm going to put jwt check to that handler and 'serializeState' function will do nothing but serialization. And maybe it will be enough to use default serialization function without redefining it by user.

**Comment by MrCheater** [comment]
Fixed in version 0.25.0
