### ISSUE TITLE
Client should resubscribe on error for AWS IoT

### ISSUE THREAD

**Issue by iokhotnikov** [reimagined/resolve#925]
After some time MQTT adapter returns 403 (Forbidden) error looks like it should resubscribe on error for AWS IoT

![screenshot 2018-12-13 at 15 02 06](https://user-images.githubusercontent.com/16080854/49938503-2e28de00-feeb-11e8-91da-4183024ec3fc.png)

![screenshot 2018-12-13 at 17 31 19](https://user-images.githubusercontent.com/16080854/49945067-06db0c80-fefd-11e8-920b-d4745b7acd85.png)

**Comment by MrCheater** [comment]
Fixed in version 0.20.6
