### ISSUE TITLE
JWT initial state contains user information even if token is invalid

### ISSUE THREAD

**Issue by timbset** [reimagined/resolve#945]
In the app I check if there is user information in redux store. If I have this information, I continue working with app (e.g. to render data loaded from read model). Else client should redirect page to authentication API. The problem is that if I have invalid token (it is expired or secret on server side is changed), I still have information about user but I cannot get data from read model. In first case this is only token deconding, without verifying. So there are two cases to fix the issue:
1. Use read model data as an authentication checker, but I have no reason why jwt redux state can be necessary if it is not actual.
2. Use verifying for jwt decoding.

I think that case 2 is much better. I understand that we cannot pass jwt secret into resolve so my suggestion is to pass `signToken` and `verifyToken` callbacks through config. They will be used in resolve and resolve will have no secure information at the same time.

**Comment by MrCheater** [comment]
Fixed in 0.21.0
