### ISSUE TITLE
Debug logs formatting

### ISSUE THREAD

**Issue by iokhotnikov** [reimagined/resolve#947]
Please make debug logs more informative.
For now it looks like some logs are redundant and unformatted properly (missed JSON.stringify() ?)

For example: 
<img width="544" alt="screenshot 2018-12-21 at 13 35 06" src="https://user-images.githubusercontent.com/16080854/50338720-48d00800-0526-11e9-8024-933c43df3ff7.png">

**Comment by superroma** [comment]
And add several level of tracing please, controlled by env variable ("DEBUG"?) - in some standard way
