### ISSUE TITLE
Describe how to configure storage adapter

### ISSUE THREAD

**Issue by superroma** [reimagined/resolve#968]
**Describe the bug**
The only explanation of the storage adapter configuration is outdated.

**To Reproduce**

https://github.com/reimagined/resolve/blob/master/docs/read-side.md#configuring-read-models

**Expected behavior**
It would be great to have a correct examples of adapter configuration for all supported platforms.

**Comment by EugeniyBurmistrov** [comment]
The topic is updated to provide the correct information
