### ISSUE TITLE
Implement store.waitForInit() in read-model resolvers

### ISSUE THREAD

**Issue by alexslavr** [reimagined/resolve#987]
Implement store.waitForInit() in read-model resolvers

**Comment by IhostVlad** [comment]
Implemented in this PR https://github.com/reimagined/resolve/pull/988, feature will be published in next release

Usage: `await store.waitEventCausalConsistency(true)` , which means wait only for `Init` function in read-model

**Comment by IhostVlad** [comment]
Implemented in resolve version 0.19.6
